;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/amp
  (:nicknames #:aws/amp)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/amp)
(common-lisp:progn
 (common-lisp:defstruct (access-denied-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'access-denied-exception 'make-access-denied-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          access-denied-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:progn
 (common-lisp:defstruct (conflict-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-id-type (common-lisp:error ":resourceid is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-type-type (common-lisp:error ":resourcetype is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'conflict-exception 'make-conflict-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          conflict-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-id)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-type))))))
(common-lisp:progn
 (common-lisp:defstruct (create-workspace-request (:copier common-lisp:nil))
   (alias-type common-lisp:nil :type
    (common-lisp:or workspace-alias common-lisp:null))
   (client-token-type common-lisp:nil :type
    (common-lisp:or idempotency-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-workspace-request 'make-create-workspace-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-workspace-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "alias"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'alias)))
    (aws-sdk-cl/generator/shape::to-query-params "clientToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-token))))))
(common-lisp:progn
 (common-lisp:defstruct (create-workspace-response (:copier common-lisp:nil))
   (arn-type (common-lisp:error ":arn is required") :type
    (common-lisp:or workspace-arn common-lisp:null))
   (status-type (common-lisp:error ":status is required") :type
    (common-lisp:or workspace-status common-lisp:null))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-workspace-response
                    'make-create-workspace-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-workspace-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn)))
    (aws-sdk-cl/generator/shape::to-query-params "status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-workspace-request (:copier common-lisp:nil))
   (client-token-type common-lisp:nil :type
    (common-lisp:or idempotency-token common-lisp:null))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-workspace-request 'make-delete-workspace-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-workspace-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "clientToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-token)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-workspace-request (:copier common-lisp:nil))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-workspace-request
                    'make-describe-workspace-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-workspace-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:progn
 (common-lisp:defstruct (describe-workspace-response (:copier common-lisp:nil))
   (workspace-type (common-lisp:error ":workspace is required") :type
    (common-lisp:or workspace-description common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-workspace-response
                    'make-describe-workspace-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-workspace-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "workspace"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace))))))
(common-lisp:deftype idempotency-token () 'common-lisp:string)
(common-lisp:deftype integer () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (internal-server-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (retry-after-seconds-type common-lisp:nil :type
    (common-lisp:or integer common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'internal-server-exception
                    'make-internal-server-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          internal-server-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "retryAfterSeconds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'retry-after-seconds))))))
(common-lisp:progn
 (common-lisp:defstruct (list-workspaces-request (:copier common-lisp:nil))
   (alias-type common-lisp:nil :type
    (common-lisp:or workspace-alias common-lisp:null))
   (max-results-type common-lisp:nil :type
    (common-lisp:or list-workspaces-request-max-results-integer
                    common-lisp:null))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-workspaces-request 'make-list-workspaces-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-workspaces-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "alias"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'alias)))
    (aws-sdk-cl/generator/shape::to-query-params "maxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:deftype list-workspaces-request-max-results-integer ()
  'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (list-workspaces-response (:copier common-lisp:nil))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null))
   (workspaces-type (common-lisp:error ":workspaces is required") :type
    (common-lisp:or workspace-summary-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-workspaces-response 'make-list-workspaces-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-workspaces-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaces"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspaces))))))
(common-lisp:deftype pagination-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (resource-not-found-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-id-type (common-lisp:error ":resourceid is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-type-type (common-lisp:error ":resourcetype is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-not-found-exception
                    'make-resource-not-found-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          resource-not-found-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-id)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-type))))))
(common-lisp:progn
 (common-lisp:defstruct
     (service-quota-exceeded-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (quota-code-type (common-lisp:error ":quotacode is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-id-type (common-lisp:error ":resourceid is required") :type
    (common-lisp:or string common-lisp:null))
   (resource-type-type (common-lisp:error ":resourcetype is required") :type
    (common-lisp:or string common-lisp:null))
   (service-code-type (common-lisp:error ":servicecode is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'service-quota-exceeded-exception
                    'make-service-quota-exceeded-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          service-quota-exceeded-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "quotaCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'quota-code)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-id)))
    (aws-sdk-cl/generator/shape::to-query-params "resourceType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-type)))
    (aws-sdk-cl/generator/shape::to-query-params "serviceCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'service-code))))))
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (throttling-exception (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (quota-code-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (retry-after-seconds-type common-lisp:nil :type
    (common-lisp:or integer common-lisp:null))
   (service-code-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'throttling-exception 'make-throttling-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          throttling-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "quotaCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'quota-code)))
    (aws-sdk-cl/generator/shape::to-query-params "retryAfterSeconds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'retry-after-seconds)))
    (aws-sdk-cl/generator/shape::to-query-params "serviceCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'service-code))))))
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (update-workspace-alias-request (:copier common-lisp:nil))
   (alias-type common-lisp:nil :type
    (common-lisp:or workspace-alias common-lisp:null))
   (client-token-type common-lisp:nil :type
    (common-lisp:or idempotency-token common-lisp:null))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-workspace-alias-request
                    'make-update-workspace-alias-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-workspace-alias-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "alias"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'alias)))
    (aws-sdk-cl/generator/shape::to-query-params "clientToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-token)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:deftype uri () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (validation-exception (:copier common-lisp:nil))
   (field-list-type common-lisp:nil :type
    (common-lisp:or validation-exception-field-list common-lisp:null))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (reason-type (common-lisp:error ":reason is required") :type
    (common-lisp:or validation-exception-reason common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'validation-exception 'make-validation-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          validation-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "fieldList"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'field-list)))
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "reason"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'reason))))))
(common-lisp:progn
 (common-lisp:defstruct (validation-exception-field (:copier common-lisp:nil))
   (message-type (common-lisp:error ":message is required") :type
    (common-lisp:or string common-lisp:null))
   (name-type (common-lisp:error ":name is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'validation-exception-field
                    'make-validation-exception-field))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          validation-exception-field))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message)))
    (aws-sdk-cl/generator/shape::to-query-params "name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name))))))
(common-lisp:progn
 (common-lisp:deftype validation-exception-field-list ()
   '(trivial-types:proper-list validation-exception-field))
 (common-lisp:defun |make-validation-exception-field-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list
                            validation-exception-field))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype validation-exception-reason () 'common-lisp:string)
(common-lisp:deftype workspace-alias () 'common-lisp:string)
(common-lisp:deftype workspace-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (workspace-description (:copier common-lisp:nil))
   (alias-type common-lisp:nil :type
    (common-lisp:or workspace-alias common-lisp:null))
   (arn-type (common-lisp:error ":arn is required") :type
    (common-lisp:or workspace-arn common-lisp:null))
   (created-at-type (common-lisp:error ":createdat is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (prometheus-endpoint-type common-lisp:nil :type
    (common-lisp:or uri common-lisp:null))
   (status-type (common-lisp:error ":status is required") :type
    (common-lisp:or workspace-status common-lisp:null))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'workspace-description 'make-workspace-description))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          workspace-description))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "alias"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'alias)))
    (aws-sdk-cl/generator/shape::to-query-params "arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn)))
    (aws-sdk-cl/generator/shape::to-query-params "createdAt"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'created-at)))
    (aws-sdk-cl/generator/shape::to-query-params "prometheusEndpoint"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'prometheus-endpoint)))
    (aws-sdk-cl/generator/shape::to-query-params "status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:deftype workspace-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (workspace-status (:copier common-lisp:nil))
   (status-code-type (common-lisp:error ":statuscode is required") :type
    (common-lisp:or workspace-status-code common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'workspace-status 'make-workspace-status))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape workspace-status))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "statusCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status-code))))))
(common-lisp:deftype workspace-status-code () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (workspace-summary (:copier common-lisp:nil))
   (alias-type common-lisp:nil :type
    (common-lisp:or workspace-alias common-lisp:null))
   (arn-type (common-lisp:error ":arn is required") :type
    (common-lisp:or workspace-arn common-lisp:null))
   (created-at-type (common-lisp:error ":createdat is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (status-type (common-lisp:error ":status is required") :type
    (common-lisp:or workspace-status common-lisp:null))
   (workspace-id-type (common-lisp:error ":workspaceid is required") :type
    (common-lisp:or workspace-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'workspace-summary 'make-workspace-summary))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape workspace-summary))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "alias"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'alias)))
    (aws-sdk-cl/generator/shape::to-query-params "arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn)))
    (aws-sdk-cl/generator/shape::to-query-params "createdAt"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'created-at)))
    (aws-sdk-cl/generator/shape::to-query-params "status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "workspaceId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'workspace-id))))))
(common-lisp:progn
 (common-lisp:deftype workspace-summary-list ()
   '(trivial-types:proper-list workspace-summary))
 (common-lisp:defun |make-workspace-summary-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list workspace-summary))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defun create-workspace
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key alias client-token)
   (common-lisp:declare (common-lisp:ignorable alias client-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-create-workspace-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "amp" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateWorkspace")
                                     ("Version" ,@"2020-08-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateWorkspaceResponse" common-lisp:nil)))
 (common-lisp:export 'create-workspace))
(common-lisp:progn
 (common-lisp:defun delete-workspace
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key client-token workspace-id)
   (common-lisp:declare (common-lisp:ignorable client-token workspace-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-delete-workspace-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "amp" :method :delete :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteWorkspace")
                                     ("Version" ,@"2020-08-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'delete-workspace))
(common-lisp:progn
 (common-lisp:defun describe-workspace
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key workspace-id)
   (common-lisp:declare (common-lisp:ignorable workspace-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-describe-workspace-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "amp" :method :get :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeWorkspace")
                                     ("Version" ,@"2020-08-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DescribeWorkspaceResponse" common-lisp:nil)))
 (common-lisp:export 'describe-workspace))
(common-lisp:progn
 (common-lisp:defun list-workspaces
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key alias max-results next-token)
   (common-lisp:declare (common-lisp:ignorable alias max-results next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-workspaces-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "amp" :method :get :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListWorkspaces")
                                     ("Version" ,@"2020-08-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListWorkspacesResponse" common-lisp:nil)))
 (common-lisp:export 'list-workspaces))
(common-lisp:progn
 (common-lisp:defun update-workspace-alias
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key alias client-token workspace-id)
   (common-lisp:declare
    (common-lisp:ignorable alias client-token workspace-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-update-workspace-alias-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "amp" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"UpdateWorkspaceAlias")
                                     ("Version" ,@"2020-08-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'update-workspace-alias))
