;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/cloud9
  (:use)
  (:nicknames #:aws/cloud9)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/cloud9)
(common-lisp:deftype automatic-stop-time-minutes () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:deftype bounded-environment-id-list ()
   '(trivial-types:proper-list environment-id))
 (common-lisp:defun |make-bounded-environment-id-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list environment-id))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype client-request-token () 'common-lisp:string)
(common-lisp:deftype connection-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (create-environment-ec2request (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null))
   (description common-lisp:nil :type
    (common-lisp:or environment-description common-lisp:null))
   (client-request-token common-lisp:nil :type
    (common-lisp:or client-request-token common-lisp:null))
   (instance-type (common-lisp:error ":instancetype is required") :type
    (common-lisp:or instance-type common-lisp:null))
   (subnet-id common-lisp:nil :type
    (common-lisp:or subnet-id common-lisp:null))
   (automatic-stop-time-minutes common-lisp:nil :type
    (common-lisp:or automatic-stop-time-minutes common-lisp:null))
   (owner-arn common-lisp:nil :type (common-lisp:or user-arn common-lisp:null))
   (tags common-lisp:nil :type (common-lisp:or tag-list common-lisp:null))
   (connection-type common-lisp:nil :type
    (common-lisp:or connection-type common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-ec2request
                    'make-create-environment-ec2request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-ec2request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "description"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'description)))
    (aws-sdk-cl/generator/shape::to-query-params "clientRequestToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-request-token)))
    (aws-sdk-cl/generator/shape::to-query-params "instanceType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'instance-type)))
    (aws-sdk-cl/generator/shape::to-query-params "subnetId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'subnet-id)))
    (aws-sdk-cl/generator/shape::to-query-params "automaticStopTimeMinutes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'automatic-stop-time-minutes)))
    (aws-sdk-cl/generator/shape::to-query-params "ownerArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'owner-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags)))
    (aws-sdk-cl/generator/shape::to-query-params "connectionType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'connection-type))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-environment-ec2result (:copier common-lisp:nil))
   (environment-id common-lisp:nil :type
    (common-lisp:or environment-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-ec2result
                    'make-create-environment-ec2result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-ec2result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-environment-membership-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null))
   (user-arn (common-lisp:error ":userarn is required") :type
    (common-lisp:or user-arn common-lisp:null))
   (permissions (common-lisp:error ":permissions is required") :type
    (common-lisp:or member-permissions common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-membership-request
                    'make-create-environment-membership-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-membership-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "userArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "permissions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'permissions))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-environment-membership-result (:copier common-lisp:nil))
   (membership common-lisp:nil :type
    (common-lisp:or environment-member common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-membership-result
                    'make-create-environment-membership-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-membership-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "membership"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'membership))))))
(common-lisp:progn
 (common-lisp:defstruct
     (delete-environment-membership-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null))
   (user-arn (common-lisp:error ":userarn is required") :type
    (common-lisp:or user-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-membership-request
                    'make-delete-environment-membership-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-membership-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "userArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (delete-environment-membership-result (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-membership-result
                    'make-delete-environment-membership-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-membership-result))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (delete-environment-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-request
                    'make-delete-environment-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-environment-result (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-result
                    'make-delete-environment-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-result))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environment-memberships-request (:copier common-lisp:nil))
   (user-arn common-lisp:nil :type (common-lisp:or user-arn common-lisp:null))
   (environment-id common-lisp:nil :type
    (common-lisp:or environment-id common-lisp:null))
   (permissions common-lisp:nil :type
    (common-lisp:or permissions-list common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environment-memberships-request
                    'make-describe-environment-memberships-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environment-memberships-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "userArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "permissions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'permissions)))
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "maxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environment-memberships-result (:copier common-lisp:nil))
   (memberships common-lisp:nil :type
    (common-lisp:or environment-members-list common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environment-memberships-result
                    'make-describe-environment-memberships-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environment-memberships-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "memberships"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'memberships)))
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environment-status-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environment-status-request
                    'make-describe-environment-status-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environment-status-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environment-status-result (:copier common-lisp:nil))
   (status common-lisp:nil :type
    (common-lisp:or environment-status common-lisp:null))
   (message common-lisp:nil :type (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environment-status-result
                    'make-describe-environment-status-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environment-status-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environments-request (:copier common-lisp:nil))
   (environment-ids (common-lisp:error ":environmentids is required") :type
    (common-lisp:or bounded-environment-id-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environments-request
                    'make-describe-environments-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environments-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentIds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-ids))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-environments-result (:copier common-lisp:nil))
   (environments common-lisp:nil :type
    (common-lisp:or environment-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-environments-result
                    'make-describe-environments-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-environments-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environments"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environments))))))
(common-lisp:progn
 (common-lisp:defstruct (environment (:copier common-lisp:nil))
   (id common-lisp:nil :type (common-lisp:or environment-id common-lisp:null))
   (name common-lisp:nil :type
    (common-lisp:or environment-name common-lisp:null))
   (description common-lisp:nil :type
    (common-lisp:or environment-description common-lisp:null))
   (type common-lisp:nil :type
    (common-lisp:or environment-type common-lisp:null))
   (connection-type common-lisp:nil :type
    (common-lisp:or connection-type common-lisp:null))
   (arn common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (owner-arn common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (lifecycle common-lisp:nil :type
    (common-lisp:or environment-lifecycle common-lisp:null)))
 (common-lisp:export (common-lisp:list 'environment 'make-environment))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape environment))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "id"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'id)))
    (aws-sdk-cl/generator/shape::to-query-params "name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "description"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'description)))
    (aws-sdk-cl/generator/shape::to-query-params "type"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'type)))
    (aws-sdk-cl/generator/shape::to-query-params "connectionType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'connection-type)))
    (aws-sdk-cl/generator/shape::to-query-params "arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn)))
    (aws-sdk-cl/generator/shape::to-query-params "ownerArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'owner-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "lifecycle"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'lifecycle))))))
(common-lisp:deftype environment-arn () 'common-lisp:string)
(common-lisp:deftype environment-description () 'common-lisp:string)
(common-lisp:deftype environment-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype environment-id-list ()
   '(trivial-types:proper-list environment-id))
 (common-lisp:defun |make-environment-id-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list environment-id))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (environment-lifecycle (:copier common-lisp:nil))
   (status common-lisp:nil :type
    (common-lisp:or environment-lifecycle-status common-lisp:null))
   (reason common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (failure-resource common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'environment-lifecycle 'make-environment-lifecycle))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          environment-lifecycle))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "reason"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'reason)))
    (aws-sdk-cl/generator/shape::to-query-params "failureResource"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'failure-resource))))))
(common-lisp:deftype environment-lifecycle-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype environment-list ()
   '(trivial-types:proper-list environment))
 (common-lisp:defun |make-environment-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list environment))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (environment-member (:copier common-lisp:nil))
   (permissions common-lisp:nil :type
    (common-lisp:or permissions common-lisp:null))
   (user-id common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (user-arn common-lisp:nil :type (common-lisp:or user-arn common-lisp:null))
   (environment-id common-lisp:nil :type
    (common-lisp:or environment-id common-lisp:null))
   (last-access common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'environment-member 'make-environment-member))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          environment-member))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "permissions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'permissions)))
    (aws-sdk-cl/generator/shape::to-query-params "userId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-id)))
    (aws-sdk-cl/generator/shape::to-query-params "userArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "lastAccess"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'last-access))))))
(common-lisp:progn
 (common-lisp:deftype environment-members-list ()
   '(trivial-types:proper-list environment-member))
 (common-lisp:defun |make-environment-members-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list environment-member))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype environment-name () 'common-lisp:string)
(common-lisp:deftype environment-status () 'common-lisp:string)
(common-lisp:deftype environment-type () 'common-lisp:string)
(common-lisp:deftype instance-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (list-environments-request (:copier common-lisp:nil))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-environments-request
                    'make-list-environments-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-environments-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "maxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results))))))
(common-lisp:progn
 (common-lisp:defstruct (list-environments-result (:copier common-lisp:nil))
   (next-token common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (environment-ids common-lisp:nil :type
    (common-lisp:or environment-id-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-environments-result 'make-list-environments-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-environments-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "nextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "environmentIds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-ids))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-resource-request (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-resource-request
                    'make-list-tags-for-resource-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-tags-for-resource-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-resource-response (:copier common-lisp:nil))
   (tags common-lisp:nil :type (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-resource-response
                    'make-list-tags-for-resource-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-tags-for-resource-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags))))))
(common-lisp:deftype max-results () 'common-lisp:integer)
(common-lisp:deftype member-permissions () 'common-lisp:string)
(common-lisp:deftype permissions () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype permissions-list ()
   '(trivial-types:proper-list permissions))
 (common-lisp:defun |make-permissions-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list permissions))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:deftype subnet-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (tag (:copier common-lisp:nil))
   (key (common-lisp:error ":key is required") :type
    (common-lisp:or tag-key common-lisp:null))
   (value (common-lisp:error ":value is required") :type
    (common-lisp:or tag-value common-lisp:null)))
 (common-lisp:export (common-lisp:list 'tag 'make-tag))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape tag))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Key"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'key)))
    (aws-sdk-cl/generator/shape::to-query-params "Value"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'value))))))
(common-lisp:deftype tag-key () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype tag-key-list () '(trivial-types:proper-list tag-key))
 (common-lisp:defun |make-tag-key-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list tag-key))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype tag-list () '(trivial-types:proper-list tag))
 (common-lisp:defun |make-tag-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list tag))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (tag-resource-request (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null))
   (tags (common-lisp:error ":tags is required") :type
    (common-lisp:or tag-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'tag-resource-request 'make-tag-resource-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          tag-resource-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags))))))
(common-lisp:progn
 (common-lisp:defstruct (tag-resource-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'tag-resource-response 'make-tag-resource-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          tag-resource-response))
   (common-lisp:append)))
(common-lisp:deftype tag-value () 'common-lisp:string)
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (untag-resource-request (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null))
   (tag-keys (common-lisp:error ":tag-keys is required") :type
    (common-lisp:or tag-key-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'untag-resource-request 'make-untag-resource-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          untag-resource-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "TagKeys"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tag-keys))))))
(common-lisp:progn
 (common-lisp:defstruct (untag-resource-response (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'untag-resource-response 'make-untag-resource-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          untag-resource-response))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (update-environment-membership-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null))
   (user-arn (common-lisp:error ":userarn is required") :type
    (common-lisp:or user-arn common-lisp:null))
   (permissions (common-lisp:error ":permissions is required") :type
    (common-lisp:or member-permissions common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-environment-membership-request
                    'make-update-environment-membership-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-membership-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "userArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "permissions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'permissions))))))
(common-lisp:progn
 (common-lisp:defstruct
     (update-environment-membership-result (:copier common-lisp:nil))
   (membership common-lisp:nil :type
    (common-lisp:or environment-member common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-environment-membership-result
                    'make-update-environment-membership-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-membership-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "membership"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'membership))))))
(common-lisp:progn
 (common-lisp:defstruct (update-environment-request (:copier common-lisp:nil))
   (environment-id (common-lisp:error ":environmentid is required") :type
    (common-lisp:or environment-id common-lisp:null))
   (name common-lisp:nil :type
    (common-lisp:or environment-name common-lisp:null))
   (description common-lisp:nil :type
    (common-lisp:or environment-description common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-environment-request
                    'make-update-environment-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "environmentId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-id)))
    (aws-sdk-cl/generator/shape::to-query-params "name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "description"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'description))))))
(common-lisp:progn
 (common-lisp:defstruct (update-environment-result (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'update-environment-result
                    'make-update-environment-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-result))
   (common-lisp:append)))
(common-lisp:deftype user-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun create-environment-ec2
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key name description client-request-token
                     instance-type subnet-id automatic-stop-time-minutes
                     owner-arn tags connection-type)
   (common-lisp:declare
    (common-lisp:ignorable name description client-request-token instance-type
     subnet-id automatic-stop-time-minutes owner-arn tags connection-type))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-create-environment-ec2request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateEnvironmentEC2")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateEnvironmentEC2Result" common-lisp:nil)))
 (common-lisp:export 'create-environment-ec2))
(common-lisp:progn
 (common-lisp:defun create-environment-membership
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id user-arn permissions)
   (common-lisp:declare
    (common-lisp:ignorable environment-id user-arn permissions))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-create-environment-membership-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateEnvironmentMembership")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateEnvironmentMembershipResult" common-lisp:nil)))
 (common-lisp:export 'create-environment-membership))
(common-lisp:progn
 (common-lisp:defun delete-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id)
   (common-lisp:declare (common-lisp:ignorable environment-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-delete-environment-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteEnvironment")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DeleteEnvironmentResult" common-lisp:nil)))
 (common-lisp:export 'delete-environment))
(common-lisp:progn
 (common-lisp:defun delete-environment-membership
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id user-arn)
   (common-lisp:declare (common-lisp:ignorable environment-id user-arn))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-delete-environment-membership-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteEnvironmentMembership")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DeleteEnvironmentMembershipResult" common-lisp:nil)))
 (common-lisp:export 'delete-environment-membership))
(common-lisp:progn
 (common-lisp:defun describe-environment-memberships
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key user-arn environment-id permissions
                     next-token max-results)
   (common-lisp:declare
    (common-lisp:ignorable user-arn environment-id permissions next-token
     max-results))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-describe-environment-memberships-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action"
                                      ,@"DescribeEnvironmentMemberships")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DescribeEnvironmentMembershipsResult" common-lisp:nil)))
 (common-lisp:export 'describe-environment-memberships))
(common-lisp:progn
 (common-lisp:defun describe-environment-status
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id)
   (common-lisp:declare (common-lisp:ignorable environment-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-describe-environment-status-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeEnvironmentStatus")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DescribeEnvironmentStatusResult" common-lisp:nil)))
 (common-lisp:export 'describe-environment-status))
(common-lisp:progn
 (common-lisp:defun describe-environments
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-ids)
   (common-lisp:declare (common-lisp:ignorable environment-ids))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-describe-environments-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeEnvironments")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DescribeEnvironmentsResult" common-lisp:nil)))
 (common-lisp:export 'describe-environments))
(common-lisp:progn
 (common-lisp:defun list-environments
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key next-token max-results)
   (common-lisp:declare (common-lisp:ignorable next-token max-results))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-environments-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListEnvironments")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListEnvironmentsResult" common-lisp:nil)))
 (common-lisp:export 'list-environments))
(common-lisp:progn
 (common-lisp:defun list-tags-for-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn)
   (common-lisp:declare (common-lisp:ignorable resource-arn))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-tags-for-resource-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListTagsForResource")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListTagsForResourceResponse" common-lisp:nil)))
 (common-lisp:export 'list-tags-for-resource))
(common-lisp:progn
 (common-lisp:defun tag-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn tags)
   (common-lisp:declare (common-lisp:ignorable resource-arn tags))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-tag-resource-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"TagResource")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "TagResourceResponse" common-lisp:nil)))
 (common-lisp:export 'tag-resource))
(common-lisp:progn
 (common-lisp:defun untag-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn tag-keys)
   (common-lisp:declare (common-lisp:ignorable resource-arn tag-keys))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-untag-resource-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"UntagResource")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "UntagResourceResponse" common-lisp:nil)))
 (common-lisp:export 'untag-resource))
(common-lisp:progn
 (common-lisp:defun update-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id name description)
   (common-lisp:declare
    (common-lisp:ignorable environment-id name description))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-update-environment-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"UpdateEnvironment")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "UpdateEnvironmentResult" common-lisp:nil)))
 (common-lisp:export 'update-environment))
(common-lisp:progn
 (common-lisp:defun update-environment-membership
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-id user-arn permissions)
   (common-lisp:declare
    (common-lisp:ignorable environment-id user-arn permissions))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-update-environment-membership-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "cloud9" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"UpdateEnvironmentMembership")
                                     ("Version" ,@"2017-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "UpdateEnvironmentMembershipResult" common-lisp:nil)))
 (common-lisp:export 'update-environment-membership))
