;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/forecastquery
  (:use)
  (:nicknames #:aws/forecastquery)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/forecastquery)
(common-lisp:deftype arn () 'common-lisp:string)
(common-lisp:deftype attribute-name () 'common-lisp:string)
(common-lisp:deftype attribute-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (data-point (:copier common-lisp:nil))
   (timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (value common-lisp:nil :type (common-lisp:or double common-lisp:null)))
 (common-lisp:export (common-lisp:list 'data-point 'make-data-point))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape data-point))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Timestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "Value"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'value))))))
(common-lisp:deftype date-time () 'common-lisp:string)
(common-lisp:deftype double () 'common-lisp:double-float)
(common-lisp:defstruct
    (filters
     (:constructor |make-filters|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:progn
 (common-lisp:defstruct (forecast (:copier common-lisp:nil))
   (predictions common-lisp:nil :type
    (common-lisp:or predictions common-lisp:null)))
 (common-lisp:export (common-lisp:list 'forecast 'make-forecast))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape forecast))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Predictions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'predictions))))))
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:defstruct
    (predictions
     (:constructor |make-predictions|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:progn
 (common-lisp:defstruct (query-forecast-request (:copier common-lisp:nil))
   (forecast-arn (common-lisp:error ":forecast-arn is required") :type
    (common-lisp:or arn common-lisp:null))
   (start-date common-lisp:nil :type
    (common-lisp:or date-time common-lisp:null))
   (end-date common-lisp:nil :type (common-lisp:or date-time common-lisp:null))
   (filters (common-lisp:error ":filters is required") :type
    (common-lisp:or filters common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'query-forecast-request 'make-query-forecast-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          query-forecast-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ForecastArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'forecast-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "StartDate"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'start-date)))
    (aws-sdk-cl/generator/shape::to-query-params "EndDate"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'end-date)))
    (aws-sdk-cl/generator/shape::to-query-params "Filters"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'filters)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct (query-forecast-response (:copier common-lisp:nil))
   (forecast common-lisp:nil :type (common-lisp:or forecast common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'query-forecast-response 'make-query-forecast-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          query-forecast-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Forecast"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'forecast))))))
(common-lisp:deftype statistic () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype time-series () '(trivial-types:proper-list data-point))
 (common-lisp:defun |make-time-series|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list data-point))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun query-forecast
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key forecast-arn start-date end-date filters
                     next-token)
   (common-lisp:declare
    (common-lisp:ignorable forecast-arn start-date end-date filters
     next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-query-forecast-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "forecastquery" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"QueryForecast")
                                     ("Version" ,@"2018-06-26"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "QueryForecastResponse" common-lisp:nil)))
 (common-lisp:export 'query-forecast))
