;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/kinesis-video-archived-media
  (:use)
  (:nicknames #:aws/kinesis-video-archived-media)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/kinesis-video-archived-media)
(common-lisp:progn
 (common-lisp:defstruct (clip-fragment-selector (:copier common-lisp:nil))
   (fragment-selector-type
    (common-lisp:error ":fragment-selector-type is required") :type
    (common-lisp:or clip-fragment-selector-type common-lisp:null))
   (timestamp-range (common-lisp:error ":timestamp-range is required") :type
    (common-lisp:or clip-timestamp-range common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'clip-fragment-selector 'make-clip-fragment-selector))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          clip-fragment-selector))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSelectorType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-selector-type)))
    (aws-sdk-cl/generator/shape::to-query-params "TimestampRange"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp-range))))))
(common-lisp:deftype clip-fragment-selector-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (clip-timestamp-range (:copier common-lisp:nil))
   (start-timestamp (common-lisp:error ":start-timestamp is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (end-timestamp (common-lisp:error ":end-timestamp is required") :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'clip-timestamp-range 'make-clip-timestamp-range))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          clip-timestamp-range))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StartTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'start-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "EndTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'end-timestamp))))))
(common-lisp:deftype container-format () 'common-lisp:string)
(common-lisp:deftype content-type () 'common-lisp:string)
(common-lisp:deftype dashdisplay-fragment-number () 'common-lisp:string)
(common-lisp:deftype dashdisplay-fragment-timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (dashfragment-selector (:copier common-lisp:nil))
   (fragment-selector-type common-lisp:nil :type
    (common-lisp:or dashfragment-selector-type common-lisp:null))
   (timestamp-range common-lisp:nil :type
    (common-lisp:or dashtimestamp-range common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dashfragment-selector 'make-dashfragment-selector))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          dashfragment-selector))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSelectorType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-selector-type)))
    (aws-sdk-cl/generator/shape::to-query-params "TimestampRange"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp-range))))))
(common-lisp:deftype dashfragment-selector-type () 'common-lisp:string)
(common-lisp:deftype dashmax-results () 'common-lisp:integer)
(common-lisp:deftype dashplayback-mode () 'common-lisp:string)
(common-lisp:deftype dashstreaming-session-url () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (dashtimestamp-range (:copier common-lisp:nil))
   (start-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (end-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'dashtimestamp-range 'make-dashtimestamp-range))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          dashtimestamp-range))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StartTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'start-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "EndTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'end-timestamp))))))
(common-lisp:deftype expires () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (fragment (:copier common-lisp:nil))
   (fragment-number common-lisp:nil :type
    (common-lisp:or fragment-number-string common-lisp:null))
   (fragment-size-in-bytes common-lisp:nil :type
    (common-lisp:or long common-lisp:null))
   (producer-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (server-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (fragment-length-in-milliseconds common-lisp:nil :type
    (common-lisp:or long common-lisp:null)))
 (common-lisp:export (common-lisp:list 'fragment 'make-fragment))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape fragment))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "FragmentNumber"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-number)))
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSizeInBytes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-size-in-bytes)))
    (aws-sdk-cl/generator/shape::to-query-params "ProducerTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'producer-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "ServerTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'server-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "FragmentLengthInMilliseconds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-length-in-milliseconds))))))
(common-lisp:progn
 (common-lisp:deftype fragment-list () '(trivial-types:proper-list fragment))
 (common-lisp:defun |make-fragment-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list fragment))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:deftype fragment-number-list ()
   '(trivial-types:proper-list fragment-number-string))
 (common-lisp:defun |make-fragment-number-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list fragment-number-string))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype fragment-number-string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (fragment-selector (:copier common-lisp:nil))
   (fragment-selector-type
    (common-lisp:error ":fragment-selector-type is required") :type
    (common-lisp:or fragment-selector-type common-lisp:null))
   (timestamp-range (common-lisp:error ":timestamp-range is required") :type
    (common-lisp:or timestamp-range common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'fragment-selector 'make-fragment-selector))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape fragment-selector))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSelectorType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-selector-type)))
    (aws-sdk-cl/generator/shape::to-query-params "TimestampRange"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp-range))))))
(common-lisp:deftype fragment-selector-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (get-clip-input (:copier common-lisp:nil))
   (stream-name common-lisp:nil :type
    (common-lisp:or stream-name common-lisp:null))
   (stream-arn common-lisp:nil :type
    (common-lisp:or resource-arn common-lisp:null))
   (clip-fragment-selector
    (common-lisp:error ":clip-fragment-selector is required") :type
    (common-lisp:or clip-fragment-selector common-lisp:null)))
 (common-lisp:export (common-lisp:list 'get-clip-input 'make-get-clip-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape get-clip-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StreamName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StreamARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "ClipFragmentSelector"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'clip-fragment-selector))))))
(common-lisp:progn
 (common-lisp:defstruct (get-clip-output (:copier common-lisp:nil))
   (content-type common-lisp:nil :type
    (common-lisp:or content-type common-lisp:null))
   (payload common-lisp:nil :type (common-lisp:or payload common-lisp:null)))
 (common-lisp:export (common-lisp:list 'get-clip-output 'make-get-clip-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape get-clip-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ContentType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'content-type)))
    (aws-sdk-cl/generator/shape::to-query-params "Payload"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'payload))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-dashstreaming-session-urlinput (:copier common-lisp:nil))
   (stream-name common-lisp:nil :type
    (common-lisp:or stream-name common-lisp:null))
   (stream-arn common-lisp:nil :type
    (common-lisp:or resource-arn common-lisp:null))
   (playback-mode common-lisp:nil :type
    (common-lisp:or dashplayback-mode common-lisp:null))
   (display-fragment-timestamp common-lisp:nil :type
    (common-lisp:or dashdisplay-fragment-timestamp common-lisp:null))
   (display-fragment-number common-lisp:nil :type
    (common-lisp:or dashdisplay-fragment-number common-lisp:null))
   (dashfragment-selector common-lisp:nil :type
    (common-lisp:or dashfragment-selector common-lisp:null))
   (expires common-lisp:nil :type (common-lisp:or expires common-lisp:null))
   (max-manifest-fragment-results common-lisp:nil :type
    (common-lisp:or dashmax-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-dashstreaming-session-urlinput
                    'make-get-dashstreaming-session-urlinput))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-dashstreaming-session-urlinput))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StreamName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StreamARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "PlaybackMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'playback-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "DisplayFragmentTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'display-fragment-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "DisplayFragmentNumber"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'display-fragment-number)))
    (aws-sdk-cl/generator/shape::to-query-params "DASHFragmentSelector"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dashfragment-selector)))
    (aws-sdk-cl/generator/shape::to-query-params "Expires"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'expires)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxManifestFragmentResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-manifest-fragment-results))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-dashstreaming-session-urloutput (:copier common-lisp:nil))
   (dashstreaming-session-url common-lisp:nil :type
    (common-lisp:or dashstreaming-session-url common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-dashstreaming-session-urloutput
                    'make-get-dashstreaming-session-urloutput))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-dashstreaming-session-urloutput))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DASHStreamingSessionURL"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dashstreaming-session-url))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-hlsstreaming-session-urlinput (:copier common-lisp:nil))
   (stream-name common-lisp:nil :type
    (common-lisp:or stream-name common-lisp:null))
   (stream-arn common-lisp:nil :type
    (common-lisp:or resource-arn common-lisp:null))
   (playback-mode common-lisp:nil :type
    (common-lisp:or hlsplayback-mode common-lisp:null))
   (hlsfragment-selector common-lisp:nil :type
    (common-lisp:or hlsfragment-selector common-lisp:null))
   (container-format common-lisp:nil :type
    (common-lisp:or container-format common-lisp:null))
   (discontinuity-mode common-lisp:nil :type
    (common-lisp:or hlsdiscontinuity-mode common-lisp:null))
   (display-fragment-timestamp common-lisp:nil :type
    (common-lisp:or hlsdisplay-fragment-timestamp common-lisp:null))
   (expires common-lisp:nil :type (common-lisp:or expires common-lisp:null))
   (max-media-playlist-fragment-results common-lisp:nil :type
    (common-lisp:or hlsmax-results common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-hlsstreaming-session-urlinput
                    'make-get-hlsstreaming-session-urlinput))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-hlsstreaming-session-urlinput))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StreamName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StreamARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "PlaybackMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'playback-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "HLSFragmentSelector"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'hlsfragment-selector)))
    (aws-sdk-cl/generator/shape::to-query-params "ContainerFormat"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'container-format)))
    (aws-sdk-cl/generator/shape::to-query-params "DiscontinuityMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'discontinuity-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "DisplayFragmentTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'display-fragment-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "Expires"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'expires)))
    (aws-sdk-cl/generator/shape::to-query-params
     "MaxMediaPlaylistFragmentResults"
     (aws-sdk-cl/generator/shape:shape-to-params
      (common-lisp:slot-value aws-sdk-cl/generator/shape::shape
                              'max-media-playlist-fragment-results))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-hlsstreaming-session-urloutput (:copier common-lisp:nil))
   (hlsstreaming-session-url common-lisp:nil :type
    (common-lisp:or hlsstreaming-session-url common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-hlsstreaming-session-urloutput
                    'make-get-hlsstreaming-session-urloutput))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-hlsstreaming-session-urloutput))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HLSStreamingSessionURL"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'hlsstreaming-session-url))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-media-for-fragment-list-input (:copier common-lisp:nil))
   (stream-name common-lisp:nil :type
    (common-lisp:or stream-name common-lisp:null))
   (stream-arn common-lisp:nil :type
    (common-lisp:or resource-arn common-lisp:null))
   (fragments (common-lisp:error ":fragments is required") :type
    (common-lisp:or fragment-number-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-media-for-fragment-list-input
                    'make-get-media-for-fragment-list-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-media-for-fragment-list-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StreamName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StreamARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Fragments"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragments))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-media-for-fragment-list-output (:copier common-lisp:nil))
   (content-type common-lisp:nil :type
    (common-lisp:or content-type common-lisp:null))
   (payload common-lisp:nil :type (common-lisp:or payload common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-media-for-fragment-list-output
                    'make-get-media-for-fragment-list-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-media-for-fragment-list-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ContentType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'content-type)))
    (aws-sdk-cl/generator/shape::to-query-params "Payload"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'payload))))))
(common-lisp:deftype hlsdiscontinuity-mode () 'common-lisp:string)
(common-lisp:deftype hlsdisplay-fragment-timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (hlsfragment-selector (:copier common-lisp:nil))
   (fragment-selector-type common-lisp:nil :type
    (common-lisp:or hlsfragment-selector-type common-lisp:null))
   (timestamp-range common-lisp:nil :type
    (common-lisp:or hlstimestamp-range common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'hlsfragment-selector 'make-hlsfragment-selector))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          hlsfragment-selector))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSelectorType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-selector-type)))
    (aws-sdk-cl/generator/shape::to-query-params "TimestampRange"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp-range))))))
(common-lisp:deftype hlsfragment-selector-type () 'common-lisp:string)
(common-lisp:deftype hlsmax-results () 'common-lisp:integer)
(common-lisp:deftype hlsplayback-mode () 'common-lisp:string)
(common-lisp:deftype hlsstreaming-session-url () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (hlstimestamp-range (:copier common-lisp:nil))
   (start-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (end-timestamp common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'hlstimestamp-range 'make-hlstimestamp-range))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          hlstimestamp-range))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StartTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'start-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "EndTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'end-timestamp))))))
(common-lisp:progn
 (common-lisp:defstruct (list-fragments-input (:copier common-lisp:nil))
   (stream-name common-lisp:nil :type
    (common-lisp:or stream-name common-lisp:null))
   (stream-arn common-lisp:nil :type
    (common-lisp:or resource-arn common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or list-fragments-max-results common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null))
   (fragment-selector common-lisp:nil :type
    (common-lisp:or fragment-selector common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-fragments-input 'make-list-fragments-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-fragments-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StreamName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StreamARN"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'stream-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "FragmentSelector"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragment-selector))))))
(common-lisp:deftype list-fragments-max-results () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (list-fragments-output (:copier common-lisp:nil))
   (fragments common-lisp:nil :type
    (common-lisp:or fragment-list common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-fragments-output 'make-list-fragments-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-fragments-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Fragments"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'fragments)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:deftype long () 'common-lisp:integer)
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:deftype payload ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:deftype resource-arn () 'common-lisp:string)
(common-lisp:deftype stream-name () 'common-lisp:string)
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (timestamp-range (:copier common-lisp:nil))
   (start-timestamp (common-lisp:error ":start-timestamp is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (end-timestamp (common-lisp:error ":end-timestamp is required") :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export (common-lisp:list 'timestamp-range 'make-timestamp-range))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape timestamp-range))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "StartTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'start-timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "EndTimestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'end-timestamp))))))
(common-lisp:progn
 (common-lisp:defun get-clip
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key stream-name stream-arn
                     clip-fragment-selector)
   (common-lisp:declare
    (common-lisp:ignorable stream-name stream-arn clip-fragment-selector))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-get-clip-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "kinesis-video-archived-media"
                                  :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetClip")
                                     ("Version" ,@"2017-09-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetClipOutput" common-lisp:nil)))
 (common-lisp:export 'get-clip))
(common-lisp:progn
 (common-lisp:defun get-dashstreaming-session-url
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key stream-name stream-arn playback-mode
                     display-fragment-timestamp display-fragment-number
                     dashfragment-selector expires
                     max-manifest-fragment-results)
   (common-lisp:declare
    (common-lisp:ignorable stream-name stream-arn playback-mode
     display-fragment-timestamp display-fragment-number dashfragment-selector
     expires max-manifest-fragment-results))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-get-dashstreaming-session-urlinput
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "kinesis-video-archived-media"
                                  :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetDASHStreamingSessionURL")
                                     ("Version" ,@"2017-09-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetDASHStreamingSessionURLOutput" common-lisp:nil)))
 (common-lisp:export 'get-dashstreaming-session-url))
(common-lisp:progn
 (common-lisp:defun get-hlsstreaming-session-url
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key stream-name stream-arn playback-mode
                     hlsfragment-selector container-format discontinuity-mode
                     display-fragment-timestamp expires
                     max-media-playlist-fragment-results)
   (common-lisp:declare
    (common-lisp:ignorable stream-name stream-arn playback-mode
     hlsfragment-selector container-format discontinuity-mode
     display-fragment-timestamp expires max-media-playlist-fragment-results))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-get-hlsstreaming-session-urlinput
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "kinesis-video-archived-media"
                                  :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetHLSStreamingSessionURL")
                                     ("Version" ,@"2017-09-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetHLSStreamingSessionURLOutput" common-lisp:nil)))
 (common-lisp:export 'get-hlsstreaming-session-url))
(common-lisp:progn
 (common-lisp:defun get-media-for-fragment-list
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key stream-name stream-arn fragments)
   (common-lisp:declare
    (common-lisp:ignorable stream-name stream-arn fragments))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-get-media-for-fragment-list-input
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "kinesis-video-archived-media"
                                  :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetMediaForFragmentList")
                                     ("Version" ,@"2017-09-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetMediaForFragmentListOutput" common-lisp:nil)))
 (common-lisp:export 'get-media-for-fragment-list))
(common-lisp:progn
 (common-lisp:defun list-fragments
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key stream-name stream-arn max-results
                     next-token fragment-selector)
   (common-lisp:declare
    (common-lisp:ignorable stream-name stream-arn max-results next-token
     fragment-selector))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-fragments-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "kinesis-video-archived-media"
                                  :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListFragments")
                                     ("Version" ,@"2017-09-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListFragmentsOutput" common-lisp:nil)))
 (common-lisp:export 'list-fragments))
