;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/migrationhub-config
  (:use)
  (:nicknames #:aws/migrationhub-config)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/migrationhub-config)
(common-lisp:deftype control-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (create-home-region-control-request (:copier common-lisp:nil))
   (home-region (common-lisp:error ":home-region is required") :type
    (common-lisp:or home-region common-lisp:null))
   (target (common-lisp:error ":target is required") :type
    (common-lisp:or target common-lisp:null))
   (dry-run common-lisp:nil :type (common-lisp:or dry-run common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-home-region-control-request
                    'make-create-home-region-control-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-home-region-control-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region)))
    (aws-sdk-cl/generator/shape::to-query-params "Target"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'target)))
    (aws-sdk-cl/generator/shape::to-query-params "DryRun"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dry-run))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-home-region-control-result (:copier common-lisp:nil))
   (home-region-control common-lisp:nil :type
    (common-lisp:or home-region-control common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-home-region-control-result
                    'make-create-home-region-control-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-home-region-control-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegionControl"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region-control))))))
(common-lisp:deftype describe-home-region-controls-max-results ()
  'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct
     (describe-home-region-controls-request (:copier common-lisp:nil))
   (control-id common-lisp:nil :type
    (common-lisp:or control-id common-lisp:null))
   (home-region common-lisp:nil :type
    (common-lisp:or home-region common-lisp:null))
   (target common-lisp:nil :type (common-lisp:or target common-lisp:null))
   (max-results common-lisp:nil :type
    (common-lisp:or describe-home-region-controls-max-results
                    common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-home-region-controls-request
                    'make-describe-home-region-controls-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-home-region-controls-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ControlId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'control-id)))
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region)))
    (aws-sdk-cl/generator/shape::to-query-params "Target"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'target)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (describe-home-region-controls-result (:copier common-lisp:nil))
   (home-region-controls common-lisp:nil :type
    (common-lisp:or home-region-controls common-lisp:null))
   (next-token common-lisp:nil :type (common-lisp:or token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'describe-home-region-controls-result
                    'make-describe-home-region-controls-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          describe-home-region-controls-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegionControls"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region-controls)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:deftype dry-run () 'common-lisp:boolean)
(common-lisp:progn
 (common-lisp:defstruct (get-home-region-request (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'get-home-region-request 'make-get-home-region-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-home-region-request))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (get-home-region-result (:copier common-lisp:nil))
   (home-region common-lisp:nil :type
    (common-lisp:or home-region common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-home-region-result 'make-get-home-region-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-home-region-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region))))))
(common-lisp:deftype home-region () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (home-region-control (:copier common-lisp:nil))
   (control-id common-lisp:nil :type
    (common-lisp:or control-id common-lisp:null))
   (home-region common-lisp:nil :type
    (common-lisp:or home-region common-lisp:null))
   (target common-lisp:nil :type (common-lisp:or target common-lisp:null))
   (requested-time common-lisp:nil :type
    (common-lisp:or requested-time common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'home-region-control 'make-home-region-control))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          home-region-control))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ControlId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'control-id)))
    (aws-sdk-cl/generator/shape::to-query-params "HomeRegion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'home-region)))
    (aws-sdk-cl/generator/shape::to-query-params "Target"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'target)))
    (aws-sdk-cl/generator/shape::to-query-params "RequestedTime"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requested-time))))))
(common-lisp:progn
 (common-lisp:deftype home-region-controls ()
   '(trivial-types:proper-list home-region-control))
 (common-lisp:defun |make-home-region-controls|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list home-region-control))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype requested-time () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (target (:copier common-lisp:nil))
   (type (common-lisp:error ":type is required") :type
    (common-lisp:or target-type common-lisp:null))
   (id common-lisp:nil :type (common-lisp:or target-id common-lisp:null)))
 (common-lisp:export (common-lisp:list 'target 'make-target))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape target))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Type"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'type)))
    (aws-sdk-cl/generator/shape::to-query-params "Id"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'id))))))
(common-lisp:deftype target-id () 'common-lisp:string)
(common-lisp:deftype target-type () 'common-lisp:string)
(common-lisp:deftype token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun create-home-region-control
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key home-region target dry-run)
   (common-lisp:declare (common-lisp:ignorable home-region target dry-run))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-create-home-region-control-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "migrationhub-config" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateHomeRegionControl")
                                     ("Version" ,@"2019-06-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateHomeRegionControlResult" common-lisp:nil)))
 (common-lisp:export 'create-home-region-control))
(common-lisp:progn
 (common-lisp:defun describe-home-region-controls
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key control-id home-region target max-results
                     next-token)
   (common-lisp:declare
    (common-lisp:ignorable control-id home-region target max-results
     next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-describe-home-region-controls-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "migrationhub-config" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"DescribeHomeRegionControls")
                                     ("Version" ,@"2019-06-30"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DescribeHomeRegionControlsResult" common-lisp:nil)))
 (common-lisp:export 'describe-home-region-controls))
(common-lisp:progn
 (common-lisp:defun get-home-region ()
   (aws-sdk-cl/generator/operation::parse-response
    (aws-sdk-cl/api:aws-request :service "migrationhub-config" :method :post
                                :params
                                `(("Action" ,@"GetHomeRegion")
                                  ("Version" ,@"2019-06-30")))
    "GetHomeRegionResult" common-lisp:nil))
 (common-lisp:export 'get-home-region))
