;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/mwaa
  (:use)
  (:nicknames #:aws/mwaa)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/mwaa)
(common-lisp:defstruct
    (airflow-configuration-options
     (:constructor |make-airflow-configuration-options|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:deftype airflow-version () 'common-lisp:string)
(common-lisp:deftype cloud-watch-log-group-arn () 'common-lisp:string)
(common-lisp:deftype config-key () 'common-lisp:string)
(common-lisp:deftype config-value () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (create-cli-token-request (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-cli-token-request 'make-create-cli-token-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-cli-token-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name))))))
(common-lisp:progn
 (common-lisp:defstruct (create-cli-token-response (:copier common-lisp:nil))
   (cli-token common-lisp:nil :type
    (common-lisp:or synthetic-create-cli-token-response-token
                    common-lisp:null))
   (web-server-hostname common-lisp:nil :type
    (common-lisp:or hostname common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-cli-token-response
                    'make-create-cli-token-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-cli-token-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "CliToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'cli-token)))
    (aws-sdk-cl/generator/shape::to-query-params "WebServerHostname"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'web-server-hostname))))))
(common-lisp:progn
 (common-lisp:defstruct (create-environment-input (:copier common-lisp:nil))
   (airflow-configuration-options common-lisp:nil :type
    (common-lisp:or
     synthetic-create-environment-input-airflow-configuration-options
     common-lisp:null))
   (airflow-version common-lisp:nil :type
    (common-lisp:or airflow-version common-lisp:null))
   (dag-s3path (common-lisp:error ":dag-s3path is required") :type
    (common-lisp:or relative-path common-lisp:null))
   (environment-class common-lisp:nil :type
    (common-lisp:or environment-class common-lisp:null))
   (execution-role-arn (common-lisp:error ":execution-role-arn is required")
    :type (common-lisp:or iam-role-arn common-lisp:null))
   (kms-key common-lisp:nil :type (common-lisp:or kms-key common-lisp:null))
   (logging-configuration common-lisp:nil :type
    (common-lisp:or logging-configuration-input common-lisp:null))
   (max-workers common-lisp:nil :type
    (common-lisp:or max-workers common-lisp:null))
   (min-workers common-lisp:nil :type
    (common-lisp:or min-workers common-lisp:null))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null))
   (network-configuration
    (common-lisp:error ":network-configuration is required") :type
    (common-lisp:or network-configuration common-lisp:null))
   (plugins-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (plugins-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (requirements-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (requirements-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (source-bucket-arn (common-lisp:error ":source-bucket-arn is required")
    :type (common-lisp:or s3bucket-arn common-lisp:null))
   (tags common-lisp:nil :type (common-lisp:or tag-map common-lisp:null))
   (webserver-access-mode common-lisp:nil :type
    (common-lisp:or webserver-access-mode common-lisp:null))
   (weekly-maintenance-window-start common-lisp:nil :type
    (common-lisp:or weekly-maintenance-window-start common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-input 'make-create-environment-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "AirflowConfigurationOptions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-configuration-options)))
    (aws-sdk-cl/generator/shape::to-query-params "AirflowVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-version)))
    (aws-sdk-cl/generator/shape::to-query-params "DagS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dag-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "EnvironmentClass"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-class)))
    (aws-sdk-cl/generator/shape::to-query-params "ExecutionRoleArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'execution-role-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "KmsKey"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'kms-key)))
    (aws-sdk-cl/generator/shape::to-query-params "LoggingConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'logging-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "MinWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'min-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "NetworkConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'network-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "SourceBucketArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'source-bucket-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverAccessMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-access-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "WeeklyMaintenanceWindowStart"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'weekly-maintenance-window-start))))))
(common-lisp:progn
 (common-lisp:defstruct (create-environment-output (:copier common-lisp:nil))
   (arn common-lisp:nil :type
    (common-lisp:or environment-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-environment-output
                    'make-create-environment-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-environment-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-web-login-token-request (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-web-login-token-request
                    'make-create-web-login-token-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-web-login-token-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name))))))
(common-lisp:progn
 (common-lisp:defstruct
     (create-web-login-token-response (:copier common-lisp:nil))
   (web-server-hostname common-lisp:nil :type
    (common-lisp:or hostname common-lisp:null))
   (web-token common-lisp:nil :type
    (common-lisp:or synthetic-create-web-login-token-response-token
                    common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'create-web-login-token-response
                    'make-create-web-login-token-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          create-web-login-token-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "WebServerHostname"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'web-server-hostname)))
    (aws-sdk-cl/generator/shape::to-query-params "WebToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'web-token))))))
(common-lisp:deftype created-at () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (delete-environment-input (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-input 'make-delete-environment-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name))))))
(common-lisp:progn
 (common-lisp:defstruct (delete-environment-output (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'delete-environment-output
                    'make-delete-environment-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          delete-environment-output))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (dimension (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or string common-lisp:null))
   (value (common-lisp:error ":value is required") :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export (common-lisp:list 'dimension 'make-dimension))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape dimension))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "Value"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'value))))))
(common-lisp:progn
 (common-lisp:deftype dimensions () '(trivial-types:proper-list dimension))
 (common-lisp:defun |make-dimensions|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list dimension))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype double () 'common-lisp:double-float)
(common-lisp:progn
 (common-lisp:defstruct (environment (:copier common-lisp:nil))
   (airflow-configuration-options common-lisp:nil :type
    (common-lisp:or airflow-configuration-options common-lisp:null))
   (airflow-version common-lisp:nil :type
    (common-lisp:or airflow-version common-lisp:null))
   (arn common-lisp:nil :type
    (common-lisp:or environment-arn common-lisp:null))
   (created-at common-lisp:nil :type
    (common-lisp:or created-at common-lisp:null))
   (dag-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (environment-class common-lisp:nil :type
    (common-lisp:or environment-class common-lisp:null))
   (execution-role-arn common-lisp:nil :type
    (common-lisp:or iam-role-arn common-lisp:null))
   (kms-key common-lisp:nil :type (common-lisp:or kms-key common-lisp:null))
   (last-update common-lisp:nil :type
    (common-lisp:or last-update common-lisp:null))
   (logging-configuration common-lisp:nil :type
    (common-lisp:or logging-configuration common-lisp:null))
   (max-workers common-lisp:nil :type
    (common-lisp:or max-workers common-lisp:null))
   (min-workers common-lisp:nil :type
    (common-lisp:or min-workers common-lisp:null))
   (name common-lisp:nil :type
    (common-lisp:or environment-name common-lisp:null))
   (network-configuration common-lisp:nil :type
    (common-lisp:or network-configuration common-lisp:null))
   (plugins-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (plugins-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (requirements-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (requirements-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (service-role-arn common-lisp:nil :type
    (common-lisp:or iam-role-arn common-lisp:null))
   (source-bucket-arn common-lisp:nil :type
    (common-lisp:or s3bucket-arn common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or environment-status common-lisp:null))
   (tags common-lisp:nil :type (common-lisp:or tag-map common-lisp:null))
   (webserver-access-mode common-lisp:nil :type
    (common-lisp:or webserver-access-mode common-lisp:null))
   (webserver-url common-lisp:nil :type
    (common-lisp:or webserver-url common-lisp:null))
   (weekly-maintenance-window-start common-lisp:nil :type
    (common-lisp:or weekly-maintenance-window-start common-lisp:null)))
 (common-lisp:export (common-lisp:list 'environment 'make-environment))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape environment))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "AirflowConfigurationOptions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-configuration-options)))
    (aws-sdk-cl/generator/shape::to-query-params "AirflowVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-version)))
    (aws-sdk-cl/generator/shape::to-query-params "Arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn)))
    (aws-sdk-cl/generator/shape::to-query-params "CreatedAt"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'created-at)))
    (aws-sdk-cl/generator/shape::to-query-params "DagS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dag-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "EnvironmentClass"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-class)))
    (aws-sdk-cl/generator/shape::to-query-params "ExecutionRoleArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'execution-role-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "KmsKey"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'kms-key)))
    (aws-sdk-cl/generator/shape::to-query-params "LastUpdate"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'last-update)))
    (aws-sdk-cl/generator/shape::to-query-params "LoggingConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'logging-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "MinWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'min-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "NetworkConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'network-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "ServiceRoleArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'service-role-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "SourceBucketArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'source-bucket-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status)))
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverAccessMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-access-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverUrl"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-url)))
    (aws-sdk-cl/generator/shape::to-query-params "WeeklyMaintenanceWindowStart"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'weekly-maintenance-window-start))))))
(common-lisp:deftype environment-arn () 'common-lisp:string)
(common-lisp:deftype environment-class () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype environment-list ()
   '(trivial-types:proper-list environment-name))
 (common-lisp:defun |make-environment-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list environment-name))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype environment-name () 'common-lisp:string)
(common-lisp:deftype environment-status () 'common-lisp:string)
(common-lisp:deftype error-code () 'common-lisp:string)
(common-lisp:deftype error-message () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (get-environment-input (:copier common-lisp:nil))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-environment-input 'make-get-environment-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-environment-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name))))))
(common-lisp:progn
 (common-lisp:defstruct (get-environment-output (:copier common-lisp:nil))
   (environment common-lisp:nil :type
    (common-lisp:or environment common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-environment-output 'make-get-environment-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-environment-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Environment"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment))))))
(common-lisp:deftype hostname () 'common-lisp:string)
(common-lisp:deftype iam-role-arn () 'common-lisp:string)
(common-lisp:deftype integer () 'common-lisp:integer)
(common-lisp:deftype kms-key () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (last-update (:copier common-lisp:nil))
   (created-at common-lisp:nil :type
    (common-lisp:or update-created-at common-lisp:null))
   (error common-lisp:nil :type (common-lisp:or update-error common-lisp:null))
   (status common-lisp:nil :type
    (common-lisp:or update-status common-lisp:null)))
 (common-lisp:export (common-lisp:list 'last-update 'make-last-update))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape last-update))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "CreatedAt"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'created-at)))
    (aws-sdk-cl/generator/shape::to-query-params "Error"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'error)))
    (aws-sdk-cl/generator/shape::to-query-params "Status"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status))))))
(common-lisp:progn
 (common-lisp:defstruct (list-environments-input (:copier common-lisp:nil))
   (max-results common-lisp:nil :type
    (common-lisp:or list-environments-input-max-results-integer
                    common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-environments-input 'make-list-environments-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-environments-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "MaxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:deftype list-environments-input-max-results-integer ()
  'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct (list-environments-output (:copier common-lisp:nil))
   (environments (common-lisp:error ":environments is required") :type
    (common-lisp:or environment-list common-lisp:null))
   (next-token common-lisp:nil :type
    (common-lisp:or next-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-environments-output 'make-list-environments-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-environments-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Environments"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environments)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-resource-input (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-resource-input
                    'make-list-tags-for-resource-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-tags-for-resource-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn))))))
(common-lisp:progn
 (common-lisp:defstruct
     (list-tags-for-resource-output (:copier common-lisp:nil))
   (tags common-lisp:nil :type (common-lisp:or tag-map common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'list-tags-for-resource-output
                    'make-list-tags-for-resource-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          list-tags-for-resource-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags))))))
(common-lisp:progn
 (common-lisp:defstruct (logging-configuration (:copier common-lisp:nil))
   (dag-processing-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration common-lisp:null))
   (scheduler-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration common-lisp:null))
   (task-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration common-lisp:null))
   (webserver-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration common-lisp:null))
   (worker-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'logging-configuration 'make-logging-configuration))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          logging-configuration))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DagProcessingLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dag-processing-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "SchedulerLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'scheduler-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "TaskLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'task-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "WorkerLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'worker-logs))))))
(common-lisp:progn
 (common-lisp:defstruct (logging-configuration-input (:copier common-lisp:nil))
   (dag-processing-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration-input common-lisp:null))
   (scheduler-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration-input common-lisp:null))
   (task-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration-input common-lisp:null))
   (webserver-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration-input common-lisp:null))
   (worker-logs common-lisp:nil :type
    (common-lisp:or module-logging-configuration-input common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'logging-configuration-input
                    'make-logging-configuration-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          logging-configuration-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DagProcessingLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dag-processing-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "SchedulerLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'scheduler-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "TaskLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'task-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-logs)))
    (aws-sdk-cl/generator/shape::to-query-params "WorkerLogs"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'worker-logs))))))
(common-lisp:deftype logging-enabled () 'common-lisp:boolean)
(common-lisp:deftype logging-level () 'common-lisp:string)
(common-lisp:deftype max-workers () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:deftype metric-data () '(trivial-types:proper-list metric-datum))
 (common-lisp:defun |make-metric-data|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list metric-datum))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (metric-datum (:copier common-lisp:nil))
   (dimensions common-lisp:nil :type
    (common-lisp:or dimensions common-lisp:null))
   (metric-name (common-lisp:error ":metric-name is required") :type
    (common-lisp:or string common-lisp:null))
   (statistic-values common-lisp:nil :type
    (common-lisp:or statistic-set common-lisp:null))
   (timestamp (common-lisp:error ":timestamp is required") :type
    (common-lisp:or timestamp common-lisp:null))
   (unit common-lisp:nil :type (common-lisp:or unit common-lisp:null))
   (value common-lisp:nil :type (common-lisp:or double common-lisp:null)))
 (common-lisp:export (common-lisp:list 'metric-datum 'make-metric-datum))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape metric-datum))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Dimensions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dimensions)))
    (aws-sdk-cl/generator/shape::to-query-params "MetricName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'metric-name)))
    (aws-sdk-cl/generator/shape::to-query-params "StatisticValues"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'statistic-values)))
    (aws-sdk-cl/generator/shape::to-query-params "Timestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp)))
    (aws-sdk-cl/generator/shape::to-query-params "Unit"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'unit)))
    (aws-sdk-cl/generator/shape::to-query-params "Value"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'value))))))
(common-lisp:deftype min-workers () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct
     (module-logging-configuration (:copier common-lisp:nil))
   (cloud-watch-log-group-arn common-lisp:nil :type
    (common-lisp:or cloud-watch-log-group-arn common-lisp:null))
   (enabled common-lisp:nil :type
    (common-lisp:or logging-enabled common-lisp:null))
   (log-level common-lisp:nil :type
    (common-lisp:or logging-level common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'module-logging-configuration
                    'make-module-logging-configuration))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          module-logging-configuration))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "CloudWatchLogGroupArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'cloud-watch-log-group-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Enabled"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'enabled)))
    (aws-sdk-cl/generator/shape::to-query-params "LogLevel"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'log-level))))))
(common-lisp:progn
 (common-lisp:defstruct
     (module-logging-configuration-input (:copier common-lisp:nil))
   (enabled (common-lisp:error ":enabled is required") :type
    (common-lisp:or logging-enabled common-lisp:null))
   (log-level (common-lisp:error ":log-level is required") :type
    (common-lisp:or logging-level common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'module-logging-configuration-input
                    'make-module-logging-configuration-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          module-logging-configuration-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Enabled"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'enabled)))
    (aws-sdk-cl/generator/shape::to-query-params "LogLevel"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'log-level))))))
(common-lisp:progn
 (common-lisp:defstruct (network-configuration (:copier common-lisp:nil))
   (security-group-ids common-lisp:nil :type
    (common-lisp:or security-group-list common-lisp:null))
   (subnet-ids common-lisp:nil :type
    (common-lisp:or subnet-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'network-configuration 'make-network-configuration))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          network-configuration))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "SecurityGroupIds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'security-group-ids)))
    (aws-sdk-cl/generator/shape::to-query-params "SubnetIds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'subnet-ids))))))
(common-lisp:deftype next-token () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (publish-metrics-input (:copier common-lisp:nil))
   (environment-name (common-lisp:error ":environment-name is required") :type
    (common-lisp:or environment-name common-lisp:null))
   (metric-data (common-lisp:error ":metric-data is required") :type
    (common-lisp:or metric-data common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'publish-metrics-input 'make-publish-metrics-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          publish-metrics-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "EnvironmentName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-name)))
    (aws-sdk-cl/generator/shape::to-query-params "MetricData"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'metric-data))))))
(common-lisp:progn
 (common-lisp:defstruct (publish-metrics-output (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'publish-metrics-output 'make-publish-metrics-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          publish-metrics-output))
   (common-lisp:append)))
(common-lisp:deftype relative-path () 'common-lisp:string)
(common-lisp:deftype s3bucket-arn () 'common-lisp:string)
(common-lisp:deftype s3object-version () 'common-lisp:string)
(common-lisp:deftype security-group-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype security-group-list ()
   '(trivial-types:proper-list security-group-id))
 (common-lisp:defun |make-security-group-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list security-group-id))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (statistic-set (:copier common-lisp:nil))
   (maximum common-lisp:nil :type (common-lisp:or double common-lisp:null))
   (minimum common-lisp:nil :type (common-lisp:or double common-lisp:null))
   (sample-count common-lisp:nil :type
    (common-lisp:or integer common-lisp:null))
   (sum common-lisp:nil :type (common-lisp:or double common-lisp:null)))
 (common-lisp:export (common-lisp:list 'statistic-set 'make-statistic-set))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape statistic-set))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Maximum"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'maximum)))
    (aws-sdk-cl/generator/shape::to-query-params "Minimum"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'minimum)))
    (aws-sdk-cl/generator/shape::to-query-params "SampleCount"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'sample-count)))
    (aws-sdk-cl/generator/shape::to-query-params "Sum"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'sum))))))
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:deftype subnet-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype subnet-list () '(trivial-types:proper-list subnet-id))
 (common-lisp:defun |make-subnet-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list subnet-id))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype synthetic-create-cli-token-response-token ()
  'common-lisp:string)
(common-lisp:defstruct
    (synthetic-create-environment-input-airflow-configuration-options
     (:constructor
      |make-synthetic-create-environment-input-airflow-configuration-options|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:deftype synthetic-create-web-login-token-response-token ()
  'common-lisp:string)
(common-lisp:defstruct
    (synthetic-update-environment-input-airflow-configuration-options
     (:constructor
      |make-synthetic-update-environment-input-airflow-configuration-options|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:deftype tag-key () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype tag-key-list () '(trivial-types:proper-list tag-key))
 (common-lisp:defun |make-tag-key-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list tag-key))
   aws-sdk-cl/generator/shape::members))
(common-lisp:defstruct
    (tag-map
     (:constructor |make-tag-map|
      (aws-sdk-cl/generator/shape::key aws-sdk-cl/generator/shape::value)))
  aws-sdk-cl/generator/shape::key
  aws-sdk-cl/generator/shape::value)
(common-lisp:progn
 (common-lisp:defstruct (tag-resource-input (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null))
   (tags (common-lisp:error ":tags is required") :type
    (common-lisp:or tag-map common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'tag-resource-input 'make-tag-resource-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          tag-resource-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "Tags"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tags))))))
(common-lisp:progn
 (common-lisp:defstruct (tag-resource-output (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'tag-resource-output 'make-tag-resource-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          tag-resource-output))
   (common-lisp:append)))
(common-lisp:deftype tag-value () 'common-lisp:string)
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:deftype unit () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (untag-resource-input (:copier common-lisp:nil))
   (resource-arn (common-lisp:error ":resource-arn is required") :type
    (common-lisp:or environment-arn common-lisp:null))
   (tag-keys (common-lisp:error ":tagkeys is required") :type
    (common-lisp:or tag-key-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'untag-resource-input 'make-untag-resource-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          untag-resource-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "tagKeys"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tag-keys))))))
(common-lisp:progn
 (common-lisp:defstruct (untag-resource-output (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'untag-resource-output 'make-untag-resource-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          untag-resource-output))
   (common-lisp:append)))
(common-lisp:deftype update-created-at () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (update-environment-input (:copier common-lisp:nil))
   (airflow-configuration-options common-lisp:nil :type
    (common-lisp:or
     synthetic-update-environment-input-airflow-configuration-options
     common-lisp:null))
   (airflow-version common-lisp:nil :type
    (common-lisp:or airflow-version common-lisp:null))
   (dag-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (environment-class common-lisp:nil :type
    (common-lisp:or environment-class common-lisp:null))
   (execution-role-arn common-lisp:nil :type
    (common-lisp:or iam-role-arn common-lisp:null))
   (logging-configuration common-lisp:nil :type
    (common-lisp:or logging-configuration-input common-lisp:null))
   (max-workers common-lisp:nil :type
    (common-lisp:or max-workers common-lisp:null))
   (min-workers common-lisp:nil :type
    (common-lisp:or min-workers common-lisp:null))
   (name (common-lisp:error ":name is required") :type
    (common-lisp:or environment-name common-lisp:null))
   (network-configuration common-lisp:nil :type
    (common-lisp:or update-network-configuration-input common-lisp:null))
   (plugins-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (plugins-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (requirements-s3object-version common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null))
   (requirements-s3path common-lisp:nil :type
    (common-lisp:or relative-path common-lisp:null))
   (source-bucket-arn common-lisp:nil :type
    (common-lisp:or s3bucket-arn common-lisp:null))
   (webserver-access-mode common-lisp:nil :type
    (common-lisp:or webserver-access-mode common-lisp:null))
   (weekly-maintenance-window-start common-lisp:nil :type
    (common-lisp:or weekly-maintenance-window-start common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-environment-input 'make-update-environment-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "AirflowConfigurationOptions"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-configuration-options)))
    (aws-sdk-cl/generator/shape::to-query-params "AirflowVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'airflow-version)))
    (aws-sdk-cl/generator/shape::to-query-params "DagS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dag-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "EnvironmentClass"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'environment-class)))
    (aws-sdk-cl/generator/shape::to-query-params "ExecutionRoleArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'execution-role-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "LoggingConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'logging-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "MinWorkers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'min-workers)))
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "NetworkConfiguration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'network-configuration)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "PluginsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'plugins-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3ObjectVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3object-version)))
    (aws-sdk-cl/generator/shape::to-query-params "RequirementsS3Path"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'requirements-s3path)))
    (aws-sdk-cl/generator/shape::to-query-params "SourceBucketArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'source-bucket-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "WebserverAccessMode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'webserver-access-mode)))
    (aws-sdk-cl/generator/shape::to-query-params "WeeklyMaintenanceWindowStart"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'weekly-maintenance-window-start))))))
(common-lisp:progn
 (common-lisp:defstruct (update-environment-output (:copier common-lisp:nil))
   (arn common-lisp:nil :type
    (common-lisp:or environment-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-environment-output
                    'make-update-environment-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-environment-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Arn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'arn))))))
(common-lisp:progn
 (common-lisp:defstruct (update-error (:copier common-lisp:nil))
   (error-code common-lisp:nil :type
    (common-lisp:or error-code common-lisp:null))
   (error-message common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export (common-lisp:list 'update-error 'make-update-error))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape update-error))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ErrorCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'error-code)))
    (aws-sdk-cl/generator/shape::to-query-params "ErrorMessage"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'error-message))))))
(common-lisp:progn
 (common-lisp:defstruct
     (update-network-configuration-input (:copier common-lisp:nil))
   (security-group-ids (common-lisp:error ":security-group-ids is required")
    :type (common-lisp:or security-group-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'update-network-configuration-input
                    'make-update-network-configuration-input))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          update-network-configuration-input))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "SecurityGroupIds"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'security-group-ids))))))
(common-lisp:deftype update-status () 'common-lisp:string)
(common-lisp:deftype webserver-access-mode () 'common-lisp:string)
(common-lisp:deftype webserver-url () 'common-lisp:string)
(common-lisp:deftype weekly-maintenance-window-start () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun create-cli-token
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key name)
   (common-lisp:declare (common-lisp:ignorable name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-create-cli-token-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateCliToken")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateCliTokenResponse" common-lisp:nil)))
 (common-lisp:export 'create-cli-token))
(common-lisp:progn
 (common-lisp:defun create-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key airflow-configuration-options
                     airflow-version dag-s3path environment-class
                     execution-role-arn kms-key logging-configuration
                     max-workers min-workers name network-configuration
                     plugins-s3object-version plugins-s3path
                     requirements-s3object-version requirements-s3path
                     source-bucket-arn tags webserver-access-mode
                     weekly-maintenance-window-start)
   (common-lisp:declare
    (common-lisp:ignorable airflow-configuration-options airflow-version
     dag-s3path environment-class execution-role-arn kms-key
     logging-configuration max-workers min-workers name network-configuration
     plugins-s3object-version plugins-s3path requirements-s3object-version
     requirements-s3path source-bucket-arn tags webserver-access-mode
     weekly-maintenance-window-start))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-create-environment-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :put :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateEnvironment")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateEnvironmentOutput" common-lisp:nil)))
 (common-lisp:export 'create-environment))
(common-lisp:progn
 (common-lisp:defun create-web-login-token
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key name)
   (common-lisp:declare (common-lisp:ignorable name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-create-web-login-token-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"CreateWebLoginToken")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "CreateWebLoginTokenResponse" common-lisp:nil)))
 (common-lisp:export 'create-web-login-token))
(common-lisp:progn
 (common-lisp:defun delete-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key name)
   (common-lisp:declare (common-lisp:ignorable name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-delete-environment-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :delete :params
                                  (common-lisp:append
                                   `(("Action" ,@"DeleteEnvironment")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DeleteEnvironmentOutput" common-lisp:nil)))
 (common-lisp:export 'delete-environment))
(common-lisp:progn
 (common-lisp:defun get-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key name)
   (common-lisp:declare (common-lisp:ignorable name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-get-environment-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :get :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetEnvironment")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetEnvironmentOutput" common-lisp:nil)))
 (common-lisp:export 'get-environment))
(common-lisp:progn
 (common-lisp:defun list-environments
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key max-results next-token)
   (common-lisp:declare (common-lisp:ignorable max-results next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-environments-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :get :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListEnvironments")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListEnvironmentsOutput" common-lisp:nil)))
 (common-lisp:export 'list-environments))
(common-lisp:progn
 (common-lisp:defun list-tags-for-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn)
   (common-lisp:declare (common-lisp:ignorable resource-arn))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-list-tags-for-resource-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :get :params
                                  (common-lisp:append
                                   `(("Action" ,@"ListTagsForResource")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "ListTagsForResourceOutput" common-lisp:nil)))
 (common-lisp:export 'list-tags-for-resource))
(common-lisp:progn
 (common-lisp:defun publish-metrics
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key environment-name metric-data)
   (common-lisp:declare (common-lisp:ignorable environment-name metric-data))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-publish-metrics-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"PublishMetrics")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "PublishMetricsOutput" common-lisp:nil)))
 (common-lisp:export 'publish-metrics))
(common-lisp:progn
 (common-lisp:defun tag-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn tags)
   (common-lisp:declare (common-lisp:ignorable resource-arn tags))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-tag-resource-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"TagResource")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "TagResourceOutput" common-lisp:nil)))
 (common-lisp:export 'tag-resource))
(common-lisp:progn
 (common-lisp:defun untag-resource
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key resource-arn tag-keys)
   (common-lisp:declare (common-lisp:ignorable resource-arn tag-keys))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-untag-resource-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :delete :params
                                  (common-lisp:append
                                   `(("Action" ,@"UntagResource")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "UntagResourceOutput" common-lisp:nil)))
 (common-lisp:export 'untag-resource))
(common-lisp:progn
 (common-lisp:defun update-environment
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key airflow-configuration-options
                     airflow-version dag-s3path environment-class
                     execution-role-arn logging-configuration max-workers
                     min-workers name network-configuration
                     plugins-s3object-version plugins-s3path
                     requirements-s3object-version requirements-s3path
                     source-bucket-arn webserver-access-mode
                     weekly-maintenance-window-start)
   (common-lisp:declare
    (common-lisp:ignorable airflow-configuration-options airflow-version
     dag-s3path environment-class execution-role-arn logging-configuration
     max-workers min-workers name network-configuration
     plugins-s3object-version plugins-s3path requirements-s3object-version
     requirements-s3path source-bucket-arn webserver-access-mode
     weekly-maintenance-window-start))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-update-environment-input
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "mwaa" :method :patch :params
                                  (common-lisp:append
                                   `(("Action" ,@"UpdateEnvironment")
                                     ("Version" ,@"2020-07-01"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "UpdateEnvironmentOutput" common-lisp:nil)))
 (common-lisp:export 'update-environment))
