;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/personalize-events
  (:nicknames #:aws/personalize-events)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/personalize-events)
(common-lisp:deftype arn () 'common-lisp:string)
(common-lisp:deftype date () 'common-lisp:string)
(common-lisp:deftype error-message () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (event (:copier common-lisp:nil))
   (event-id-type common-lisp:nil :type
    (common-lisp:or string-type common-lisp:null))
   (event-type-type (common-lisp:error ":eventtype is required") :type
    (common-lisp:or string-type common-lisp:null))
   (event-value-type common-lisp:nil :type
    (common-lisp:or float-type common-lisp:null))
   (item-id-type common-lisp:nil :type
    (common-lisp:or item-id common-lisp:null))
   (properties-type common-lisp:nil :type
    (common-lisp:or event-properties-json common-lisp:null))
   (sent-at-type (common-lisp:error ":sentat is required") :type
    (common-lisp:or date common-lisp:null))
   (recommendation-id-type common-lisp:nil :type
    (common-lisp:or recommendation-id common-lisp:null))
   (impression-type common-lisp:nil :type
    (common-lisp:or impression common-lisp:null)))
 (common-lisp:export (common-lisp:list 'event 'make-event))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape event))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "eventId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'event-id)))
    (aws-sdk-cl/generator/shape::to-query-params "eventType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'event-type)))
    (aws-sdk-cl/generator/shape::to-query-params "eventValue"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'event-value)))
    (aws-sdk-cl/generator/shape::to-query-params "itemId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'item-id)))
    (aws-sdk-cl/generator/shape::to-query-params "properties"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'properties)))
    (aws-sdk-cl/generator/shape::to-query-params "sentAt"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'sent-at)))
    (aws-sdk-cl/generator/shape::to-query-params "recommendationId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'recommendation-id)))
    (aws-sdk-cl/generator/shape::to-query-params "impression"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'impression))))))
(common-lisp:progn
 (common-lisp:deftype event-list () '(trivial-types:proper-list event))
 (common-lisp:defun |make-event-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list event))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype event-properties-json () 'common-lisp:string)
(common-lisp:deftype float-type () 'common-lisp:single-float)
(common-lisp:progn
 (common-lisp:deftype impression () '(trivial-types:proper-list item-id))
 (common-lisp:defun |make-impression|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list item-id))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (invalid-input-exception (:copier common-lisp:nil))
   (message-type common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'invalid-input-exception 'make-invalid-input-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          invalid-input-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:progn
 (common-lisp:defstruct (item (:copier common-lisp:nil))
   (item-id-type (common-lisp:error ":itemid is required") :type
    (common-lisp:or string-type common-lisp:null))
   (properties-type common-lisp:nil :type
    (common-lisp:or item-properties common-lisp:null)))
 (common-lisp:export (common-lisp:list 'item 'make-item))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape item))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "itemId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'item-id)))
    (aws-sdk-cl/generator/shape::to-query-params "properties"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'properties))))))
(common-lisp:deftype item-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype item-list () '(trivial-types:proper-list item))
 (common-lisp:defun |make-item-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list item))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype item-properties () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (put-events-request (:copier common-lisp:nil))
   (tracking-id-type (common-lisp:error ":trackingid is required") :type
    (common-lisp:or string-type common-lisp:null))
   (user-id-type common-lisp:nil :type
    (common-lisp:or user-id common-lisp:null))
   (session-id-type (common-lisp:error ":sessionid is required") :type
    (common-lisp:or string-type common-lisp:null))
   (event-list-type (common-lisp:error ":eventlist is required") :type
    (common-lisp:or event-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-events-request 'make-put-events-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          put-events-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "trackingId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'tracking-id)))
    (aws-sdk-cl/generator/shape::to-query-params "userId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-id)))
    (aws-sdk-cl/generator/shape::to-query-params "sessionId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'session-id)))
    (aws-sdk-cl/generator/shape::to-query-params "eventList"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'event-list))))))
(common-lisp:progn
 (common-lisp:defstruct (put-items-request (:copier common-lisp:nil))
   (dataset-arn-type (common-lisp:error ":datasetarn is required") :type
    (common-lisp:or arn common-lisp:null))
   (items-type (common-lisp:error ":items is required") :type
    (common-lisp:or item-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-items-request 'make-put-items-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape put-items-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "datasetArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dataset-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "items"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'items))))))
(common-lisp:progn
 (common-lisp:defstruct (put-users-request (:copier common-lisp:nil))
   (dataset-arn-type (common-lisp:error ":datasetarn is required") :type
    (common-lisp:or arn common-lisp:null))
   (users-type (common-lisp:error ":users is required") :type
    (common-lisp:or user-list common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'put-users-request 'make-put-users-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape put-users-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "datasetArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dataset-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "users"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'users))))))
(common-lisp:deftype recommendation-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (resource-in-use-exception (:copier common-lisp:nil))
   (message-type common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-in-use-exception
                    'make-resource-in-use-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          resource-in-use-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:progn
 (common-lisp:defstruct
     (resource-not-found-exception (:copier common-lisp:nil))
   (message-type common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'resource-not-found-exception
                    'make-resource-not-found-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          resource-not-found-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:deftype string-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (user (:copier common-lisp:nil))
   (user-id-type (common-lisp:error ":userid is required") :type
    (common-lisp:or string-type common-lisp:null))
   (properties-type common-lisp:nil :type
    (common-lisp:or user-properties common-lisp:null)))
 (common-lisp:export (common-lisp:list 'user 'make-user))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape user))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "userId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'user-id)))
    (aws-sdk-cl/generator/shape::to-query-params "properties"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'properties))))))
(common-lisp:deftype user-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype user-list () '(trivial-types:proper-list user))
 (common-lisp:defun |make-user-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list user))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype user-properties () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun put-events
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key tracking-id user-id session-id
                     event-list)
   (common-lisp:declare
    (common-lisp:ignorable tracking-id user-id session-id event-list))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-put-events-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "personalize-events" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"PutEvents")
                                     ("Version" ,@"2018-03-22"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-events))
(common-lisp:progn
 (common-lisp:defun put-items
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key dataset-arn items)
   (common-lisp:declare (common-lisp:ignorable dataset-arn items))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-put-items-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "personalize-events" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"PutItems")
                                     ("Version" ,@"2018-03-22"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-items))
(common-lisp:progn
 (common-lisp:defun put-users
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key dataset-arn users)
   (common-lisp:declare (common-lisp:ignorable dataset-arn users))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-put-users-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "personalize-events" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"PutUsers")
                                     ("Version" ,@"2018-03-22"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'put-users))
