;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/sagemaker-edge
  (:nicknames #:aws/sagemaker-edge)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/sagemaker-edge)
(common-lisp:deftype cache-ttlseconds () 'common-lisp:string)
(common-lisp:deftype device-fleet-name () 'common-lisp:string)
(common-lisp:deftype device-name () 'common-lisp:string)
(common-lisp:deftype device-registration () 'common-lisp:string)
(common-lisp:deftype dimension () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (edge-metric (:copier common-lisp:nil))
   (dimension-type common-lisp:nil :type
    (common-lisp:or dimension common-lisp:null))
   (metric-name-type common-lisp:nil :type
    (common-lisp:or metric common-lisp:null))
   (value-type common-lisp:nil :type (common-lisp:or value common-lisp:null))
   (timestamp-type common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null)))
 (common-lisp:export (common-lisp:list 'edge-metric 'make-edge-metric))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape edge-metric))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Dimension"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'dimension)))
    (aws-sdk-cl/generator/shape::to-query-params "MetricName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'metric-name)))
    (aws-sdk-cl/generator/shape::to-query-params "Value"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'value)))
    (aws-sdk-cl/generator/shape::to-query-params "Timestamp"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'timestamp))))))
(common-lisp:progn
 (common-lisp:deftype edge-metrics () '(trivial-types:proper-list edge-metric))
 (common-lisp:defun |make-edge-metrics|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list edge-metric))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype error-message () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (get-device-registration-request (:copier common-lisp:nil))
   (device-name-type (common-lisp:error ":device-name is required") :type
    (common-lisp:or device-name common-lisp:null))
   (device-fleet-name-type (common-lisp:error ":device-fleet-name is required")
    :type (common-lisp:or device-fleet-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-device-registration-request
                    'make-get-device-registration-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-device-registration-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DeviceName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'device-name)))
    (aws-sdk-cl/generator/shape::to-query-params "DeviceFleetName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'device-fleet-name))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-device-registration-result (:copier common-lisp:nil))
   (device-registration-type common-lisp:nil :type
    (common-lisp:or device-registration common-lisp:null))
   (cache-ttltype common-lisp:nil :type
    (common-lisp:or cache-ttlseconds common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-device-registration-result
                    'make-get-device-registration-result))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-device-registration-result))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DeviceRegistration"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'device-registration)))
    (aws-sdk-cl/generator/shape::to-query-params "CacheTTL"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'cache-ttl))))))
(common-lisp:progn
 (common-lisp:defstruct (internal-service-exception (:copier common-lisp:nil))
   (message-type common-lisp:nil :type
    (common-lisp:or error-message common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'internal-service-exception
                    'make-internal-service-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          internal-service-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Message"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'message))))))
(common-lisp:deftype metric () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (model (:copier common-lisp:nil))
   (model-name-type common-lisp:nil :type
    (common-lisp:or model-name common-lisp:null))
   (model-version-type common-lisp:nil :type
    (common-lisp:or version common-lisp:null))
   (latest-sample-time-type common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (latest-inference-type common-lisp:nil :type
    (common-lisp:or timestamp common-lisp:null))
   (model-metrics-type common-lisp:nil :type
    (common-lisp:or edge-metrics common-lisp:null)))
 (common-lisp:export (common-lisp:list 'model 'make-model))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape model))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ModelName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'model-name)))
    (aws-sdk-cl/generator/shape::to-query-params "ModelVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'model-version)))
    (aws-sdk-cl/generator/shape::to-query-params "LatestSampleTime"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'latest-sample-time)))
    (aws-sdk-cl/generator/shape::to-query-params "LatestInference"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'latest-inference)))
    (aws-sdk-cl/generator/shape::to-query-params "ModelMetrics"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'model-metrics))))))
(common-lisp:deftype model-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype models () '(trivial-types:proper-list model))
 (common-lisp:defun |make-models|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list model))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct (send-heartbeat-request (:copier common-lisp:nil))
   (agent-metrics-type common-lisp:nil :type
    (common-lisp:or edge-metrics common-lisp:null))
   (models-type common-lisp:nil :type (common-lisp:or models common-lisp:null))
   (agent-version-type (common-lisp:error ":agent-version is required") :type
    (common-lisp:or version common-lisp:null))
   (device-name-type (common-lisp:error ":device-name is required") :type
    (common-lisp:or device-name common-lisp:null))
   (device-fleet-name-type (common-lisp:error ":device-fleet-name is required")
    :type (common-lisp:or device-fleet-name common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'send-heartbeat-request 'make-send-heartbeat-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          send-heartbeat-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "AgentMetrics"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'agent-metrics)))
    (aws-sdk-cl/generator/shape::to-query-params "Models"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'models)))
    (aws-sdk-cl/generator/shape::to-query-params "AgentVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'agent-version)))
    (aws-sdk-cl/generator/shape::to-query-params "DeviceName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'device-name)))
    (aws-sdk-cl/generator/shape::to-query-params "DeviceFleetName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'device-fleet-name))))))
(common-lisp:deftype timestamp () 'common-lisp:string)
(common-lisp:deftype value () 'common-lisp:double-float)
(common-lisp:deftype version () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defun get-device-registration
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key device-name device-fleet-name)
   (common-lisp:declare (common-lisp:ignorable device-name device-fleet-name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-get-device-registration-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "sagemaker-edge" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetDeviceRegistration")
                                     ("Version" ,@"2020-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetDeviceRegistrationResult" common-lisp:nil)))
 (common-lisp:export 'get-device-registration))
(common-lisp:progn
 (common-lisp:defun send-heartbeat
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key agent-metrics models agent-version
                     device-name device-fleet-name)
   (common-lisp:declare
    (common-lisp:ignorable agent-metrics models agent-version device-name
     device-fleet-name))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-send-heartbeat-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "sagemaker-edge" :method :post
                                  :params
                                  (common-lisp:append
                                   `(("Action" ,@"SendHeartbeat")
                                     ("Version" ,@"2020-09-23"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      common-lisp:nil common-lisp:nil)))
 (common-lisp:export 'send-heartbeat))
