;; DO NOT EDIT: File is generated by aws-sdk-cl/GENERATOR.

(common-lisp:defpackage #:aws-sdk-cl/services/textract
  (:nicknames #:aws/textract)
  (:import-from #:aws-sdk-cl/generator/shape)
  (:import-from #:aws-sdk-cl/generator/operation)
  (:import-from #:aws-sdk-cl/api))
(common-lisp:in-package #:aws-sdk-cl/services/textract)
(common-lisp:progn
 (common-lisp:defstruct (access-denied-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'access-denied-exception 'make-access-denied-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          access-denied-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (analyze-document-request (:copier common-lisp:nil))
   (document-type (common-lisp:error ":document is required") :type
    (common-lisp:or document common-lisp:null))
   (feature-types-type (common-lisp:error ":feature-types is required") :type
    (common-lisp:or feature-types common-lisp:null))
   (human-loop-config-type common-lisp:nil :type
    (common-lisp:or human-loop-config common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'analyze-document-request 'make-analyze-document-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          analyze-document-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Document"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document)))
    (aws-sdk-cl/generator/shape::to-query-params "FeatureTypes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'feature-types)))
    (aws-sdk-cl/generator/shape::to-query-params "HumanLoopConfig"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'human-loop-config))))))
(common-lisp:progn
 (common-lisp:defstruct (analyze-document-response (:copier common-lisp:nil))
   (document-metadata-type common-lisp:nil :type
    (common-lisp:or document-metadata common-lisp:null))
   (blocks-type common-lisp:nil :type
    (common-lisp:or block-list common-lisp:null))
   (human-loop-activation-output-type common-lisp:nil :type
    (common-lisp:or human-loop-activation-output common-lisp:null))
   (analyze-document-model-version-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'analyze-document-response
                    'make-analyze-document-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          analyze-document-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentMetadata"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-metadata)))
    (aws-sdk-cl/generator/shape::to-query-params "Blocks"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'blocks)))
    (aws-sdk-cl/generator/shape::to-query-params "HumanLoopActivationOutput"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'human-loop-activation-output)))
    (aws-sdk-cl/generator/shape::to-query-params "AnalyzeDocumentModelVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'analyze-document-model-version))))))
(common-lisp:progn
 (common-lisp:defstruct (bad-document-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'bad-document-exception 'make-bad-document-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          bad-document-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (block (:copier common-lisp:nil))
   (block-type-type common-lisp:nil :type
    (common-lisp:or block-type common-lisp:null))
   (confidence-type common-lisp:nil :type
    (common-lisp:or percent common-lisp:null))
   (text-type common-lisp:nil :type (common-lisp:or string common-lisp:null))
   (text-type-type common-lisp:nil :type
    (common-lisp:or text-type common-lisp:null))
   (row-index-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null))
   (column-index-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null))
   (row-span-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null))
   (column-span-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null))
   (geometry-type common-lisp:nil :type
    (common-lisp:or geometry common-lisp:null))
   (id-type common-lisp:nil :type
    (common-lisp:or non-empty-string common-lisp:null))
   (relationships-type common-lisp:nil :type
    (common-lisp:or relationship-list common-lisp:null))
   (entity-types-type common-lisp:nil :type
    (common-lisp:or entity-types common-lisp:null))
   (selection-status-type common-lisp:nil :type
    (common-lisp:or selection-status common-lisp:null))
   (page-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null)))
 (common-lisp:export (common-lisp:list 'block 'make-block))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape block))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "BlockType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'block-type)))
    (aws-sdk-cl/generator/shape::to-query-params "Confidence"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'confidence)))
    (aws-sdk-cl/generator/shape::to-query-params "Text"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'text)))
    (aws-sdk-cl/generator/shape::to-query-params "TextType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'text-type)))
    (aws-sdk-cl/generator/shape::to-query-params "RowIndex"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'row-index)))
    (aws-sdk-cl/generator/shape::to-query-params "ColumnIndex"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'column-index)))
    (aws-sdk-cl/generator/shape::to-query-params "RowSpan"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'row-span)))
    (aws-sdk-cl/generator/shape::to-query-params "ColumnSpan"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'column-span)))
    (aws-sdk-cl/generator/shape::to-query-params "Geometry"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'geometry)))
    (aws-sdk-cl/generator/shape::to-query-params "Id"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'id)))
    (aws-sdk-cl/generator/shape::to-query-params "Relationships"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'relationships)))
    (aws-sdk-cl/generator/shape::to-query-params "EntityTypes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'entity-types)))
    (aws-sdk-cl/generator/shape::to-query-params "SelectionStatus"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'selection-status)))
    (aws-sdk-cl/generator/shape::to-query-params "Page"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'page))))))
(common-lisp:progn
 (common-lisp:deftype block-list () '(trivial-types:proper-list block))
 (common-lisp:defun |make-block-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list block))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype block-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (bounding-box (:copier common-lisp:nil))
   (width-type common-lisp:nil :type (common-lisp:or float common-lisp:null))
   (height-type common-lisp:nil :type (common-lisp:or float common-lisp:null))
   (left-type common-lisp:nil :type (common-lisp:or float common-lisp:null))
   (top-type common-lisp:nil :type (common-lisp:or float common-lisp:null)))
 (common-lisp:export (common-lisp:list 'bounding-box 'make-bounding-box))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape bounding-box))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Width"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'width)))
    (aws-sdk-cl/generator/shape::to-query-params "Height"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'height)))
    (aws-sdk-cl/generator/shape::to-query-params "Left"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'left)))
    (aws-sdk-cl/generator/shape::to-query-params "Top"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'top))))))
(common-lisp:deftype client-request-token () 'common-lisp:string)
(common-lisp:deftype content-classifier () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype content-classifiers ()
   '(trivial-types:proper-list content-classifier))
 (common-lisp:defun |make-content-classifiers|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list content-classifier))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (detect-document-text-request (:copier common-lisp:nil))
   (document-type (common-lisp:error ":document is required") :type
    (common-lisp:or document common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'detect-document-text-request
                    'make-detect-document-text-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          detect-document-text-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Document"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document))))))
(common-lisp:progn
 (common-lisp:defstruct
     (detect-document-text-response (:copier common-lisp:nil))
   (document-metadata-type common-lisp:nil :type
    (common-lisp:or document-metadata common-lisp:null))
   (blocks-type common-lisp:nil :type
    (common-lisp:or block-list common-lisp:null))
   (detect-document-text-model-version-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'detect-document-text-response
                    'make-detect-document-text-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          detect-document-text-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentMetadata"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-metadata)))
    (aws-sdk-cl/generator/shape::to-query-params "Blocks"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'blocks)))
    (aws-sdk-cl/generator/shape::to-query-params
     "DetectDocumentTextModelVersion"
     (aws-sdk-cl/generator/shape:shape-to-params
      (common-lisp:slot-value aws-sdk-cl/generator/shape::shape
                              'detect-document-text-model-version))))))
(common-lisp:progn
 (common-lisp:defstruct (document (:copier common-lisp:nil))
   (bytes-type common-lisp:nil :type
    (common-lisp:or image-blob common-lisp:null))
   (s3object-type common-lisp:nil :type
    (common-lisp:or s3object common-lisp:null)))
 (common-lisp:export (common-lisp:list 'document 'make-document))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape document))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Bytes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'bytes)))
    (aws-sdk-cl/generator/shape::to-query-params "S3Object"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   's3object))))))
(common-lisp:progn
 (common-lisp:defstruct (document-location (:copier common-lisp:nil))
   (s3object-type common-lisp:nil :type
    (common-lisp:or s3object common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'document-location 'make-document-location))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape document-location))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "S3Object"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   's3object))))))
(common-lisp:progn
 (common-lisp:defstruct (document-metadata (:copier common-lisp:nil))
   (pages-type common-lisp:nil :type
    (common-lisp:or uinteger common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'document-metadata 'make-document-metadata))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape document-metadata))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Pages"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'pages))))))
(common-lisp:progn
 (common-lisp:defstruct
     (document-too-large-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'document-too-large-exception
                    'make-document-too-large-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          document-too-large-exception))
   (common-lisp:append)))
(common-lisp:deftype entity-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype entity-types () '(trivial-types:proper-list entity-type))
 (common-lisp:defun |make-entity-types|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list entity-type))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype error-code () 'common-lisp:string)
(common-lisp:deftype feature-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype feature-types ()
   '(trivial-types:proper-list feature-type))
 (common-lisp:defun |make-feature-types|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list feature-type))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype float () 'common-lisp:single-float)
(common-lisp:deftype flow-definition-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (geometry (:copier common-lisp:nil))
   (bounding-box-type common-lisp:nil :type
    (common-lisp:or bounding-box common-lisp:null))
   (polygon-type common-lisp:nil :type
    (common-lisp:or polygon common-lisp:null)))
 (common-lisp:export (common-lisp:list 'geometry 'make-geometry))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape geometry))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "BoundingBox"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'bounding-box)))
    (aws-sdk-cl/generator/shape::to-query-params "Polygon"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'polygon))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-document-analysis-request (:copier common-lisp:nil))
   (job-id-type (common-lisp:error ":job-id is required") :type
    (common-lisp:or job-id common-lisp:null))
   (max-results-type common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-document-analysis-request
                    'make-get-document-analysis-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-document-analysis-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "JobId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-id)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-document-analysis-response (:copier common-lisp:nil))
   (document-metadata-type common-lisp:nil :type
    (common-lisp:or document-metadata common-lisp:null))
   (job-status-type common-lisp:nil :type
    (common-lisp:or job-status common-lisp:null))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null))
   (blocks-type common-lisp:nil :type
    (common-lisp:or block-list common-lisp:null))
   (warnings-type common-lisp:nil :type
    (common-lisp:or warnings common-lisp:null))
   (status-message-type common-lisp:nil :type
    (common-lisp:or status-message common-lisp:null))
   (analyze-document-model-version-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-document-analysis-response
                    'make-get-document-analysis-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-document-analysis-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentMetadata"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-metadata)))
    (aws-sdk-cl/generator/shape::to-query-params "JobStatus"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-status)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "Blocks"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'blocks)))
    (aws-sdk-cl/generator/shape::to-query-params "Warnings"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'warnings)))
    (aws-sdk-cl/generator/shape::to-query-params "StatusMessage"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status-message)))
    (aws-sdk-cl/generator/shape::to-query-params "AnalyzeDocumentModelVersion"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'analyze-document-model-version))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-document-text-detection-request (:copier common-lisp:nil))
   (job-id-type (common-lisp:error ":job-id is required") :type
    (common-lisp:or job-id common-lisp:null))
   (max-results-type common-lisp:nil :type
    (common-lisp:or max-results common-lisp:null))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-document-text-detection-request
                    'make-get-document-text-detection-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-document-text-detection-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "JobId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-id)))
    (aws-sdk-cl/generator/shape::to-query-params "MaxResults"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'max-results)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token))))))
(common-lisp:progn
 (common-lisp:defstruct
     (get-document-text-detection-response (:copier common-lisp:nil))
   (document-metadata-type common-lisp:nil :type
    (common-lisp:or document-metadata common-lisp:null))
   (job-status-type common-lisp:nil :type
    (common-lisp:or job-status common-lisp:null))
   (next-token-type common-lisp:nil :type
    (common-lisp:or pagination-token common-lisp:null))
   (blocks-type common-lisp:nil :type
    (common-lisp:or block-list common-lisp:null))
   (warnings-type common-lisp:nil :type
    (common-lisp:or warnings common-lisp:null))
   (status-message-type common-lisp:nil :type
    (common-lisp:or status-message common-lisp:null))
   (detect-document-text-model-version-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'get-document-text-detection-response
                    'make-get-document-text-detection-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          get-document-text-detection-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentMetadata"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-metadata)))
    (aws-sdk-cl/generator/shape::to-query-params "JobStatus"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-status)))
    (aws-sdk-cl/generator/shape::to-query-params "NextToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'next-token)))
    (aws-sdk-cl/generator/shape::to-query-params "Blocks"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'blocks)))
    (aws-sdk-cl/generator/shape::to-query-params "Warnings"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'warnings)))
    (aws-sdk-cl/generator/shape::to-query-params "StatusMessage"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'status-message)))
    (aws-sdk-cl/generator/shape::to-query-params
     "DetectDocumentTextModelVersion"
     (aws-sdk-cl/generator/shape:shape-to-params
      (common-lisp:slot-value aws-sdk-cl/generator/shape::shape
                              'detect-document-text-model-version))))))
(common-lisp:deftype human-loop-activation-conditions-evaluation-results ()
  'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (human-loop-activation-output (:copier common-lisp:nil))
   (human-loop-arn-type common-lisp:nil :type
    (common-lisp:or human-loop-arn common-lisp:null))
   (human-loop-activation-reasons-type common-lisp:nil :type
    (common-lisp:or human-loop-activation-reasons common-lisp:null))
   (human-loop-activation-conditions-evaluation-results-type common-lisp:nil
    :type
    (common-lisp:or human-loop-activation-conditions-evaluation-results
                    common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'human-loop-activation-output
                    'make-human-loop-activation-output))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          human-loop-activation-output))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HumanLoopArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'human-loop-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "HumanLoopActivationReasons"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'human-loop-activation-reasons)))
    (aws-sdk-cl/generator/shape::to-query-params
     "HumanLoopActivationConditionsEvaluationResults"
     (aws-sdk-cl/generator/shape:shape-to-params
      (common-lisp:slot-value aws-sdk-cl/generator/shape::shape
                              'human-loop-activation-conditions-evaluation-results))))))
(common-lisp:deftype human-loop-activation-reason () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:deftype human-loop-activation-reasons ()
   '(trivial-types:proper-list human-loop-activation-reason))
 (common-lisp:defun |make-human-loop-activation-reasons|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list
                            human-loop-activation-reason))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype human-loop-arn () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (human-loop-config (:copier common-lisp:nil))
   (human-loop-name-type (common-lisp:error ":human-loop-name is required")
    :type (common-lisp:or human-loop-name common-lisp:null))
   (flow-definition-arn-type
    (common-lisp:error ":flow-definition-arn is required") :type
    (common-lisp:or flow-definition-arn common-lisp:null))
   (data-attributes-type common-lisp:nil :type
    (common-lisp:or human-loop-data-attributes common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'human-loop-config 'make-human-loop-config))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape human-loop-config))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "HumanLoopName"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'human-loop-name)))
    (aws-sdk-cl/generator/shape::to-query-params "FlowDefinitionArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'flow-definition-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "DataAttributes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'data-attributes))))))
(common-lisp:progn
 (common-lisp:defstruct (human-loop-data-attributes (:copier common-lisp:nil))
   (content-classifiers-type common-lisp:nil :type
    (common-lisp:or content-classifiers common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'human-loop-data-attributes
                    'make-human-loop-data-attributes))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          human-loop-data-attributes))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ContentClassifiers"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'content-classifiers))))))
(common-lisp:deftype human-loop-name () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (human-loop-quota-exceeded-exception (:copier common-lisp:nil))
   (resource-type-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (quota-code-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null))
   (service-code-type common-lisp:nil :type
    (common-lisp:or string common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'human-loop-quota-exceeded-exception
                    'make-human-loop-quota-exceeded-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          human-loop-quota-exceeded-exception))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ResourceType"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'resource-type)))
    (aws-sdk-cl/generator/shape::to-query-params "QuotaCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'quota-code)))
    (aws-sdk-cl/generator/shape::to-query-params "ServiceCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'service-code))))))
(common-lisp:progn
 (common-lisp:deftype id-list () '(trivial-types:proper-list non-empty-string))
 (common-lisp:defun |make-id-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list non-empty-string))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (idempotent-parameter-mismatch-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'idempotent-parameter-mismatch-exception
                    'make-idempotent-parameter-mismatch-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          idempotent-parameter-mismatch-exception))
   (common-lisp:append)))
(common-lisp:deftype image-blob ()
  '(common-lisp:simple-array (common-lisp:unsigned-byte 8) (common-lisp:*)))
(common-lisp:progn
 (common-lisp:defstruct (internal-server-error (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'internal-server-error 'make-internal-server-error))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          internal-server-error))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (invalid-job-id-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'invalid-job-id-exception 'make-invalid-job-id-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          invalid-job-id-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (invalid-kmskey-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'invalid-kmskey-exception 'make-invalid-kmskey-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          invalid-kmskey-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct
     (invalid-parameter-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'invalid-parameter-exception
                    'make-invalid-parameter-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          invalid-parameter-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (invalid-s3object-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'invalid-s3object-exception
                    'make-invalid-s3object-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          invalid-s3object-exception))
   (common-lisp:append)))
(common-lisp:deftype job-id () 'common-lisp:string)
(common-lisp:deftype job-status () 'common-lisp:string)
(common-lisp:deftype job-tag () 'common-lisp:string)
(common-lisp:deftype kmskey-id () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (limit-exceeded-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'limit-exceeded-exception 'make-limit-exceeded-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          limit-exceeded-exception))
   (common-lisp:append)))
(common-lisp:deftype max-results () 'common-lisp:integer)
(common-lisp:deftype non-empty-string () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (notification-channel (:copier common-lisp:nil))
   (snstopic-arn-type (common-lisp:error ":snstopic-arn is required") :type
    (common-lisp:or snstopic-arn common-lisp:null))
   (role-arn-type (common-lisp:error ":role-arn is required") :type
    (common-lisp:or role-arn common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'notification-channel 'make-notification-channel))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          notification-channel))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "SNSTopicArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'snstopic-arn)))
    (aws-sdk-cl/generator/shape::to-query-params "RoleArn"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'role-arn))))))
(common-lisp:progn
 (common-lisp:defstruct (output-config (:copier common-lisp:nil))
   (s3bucket-type (common-lisp:error ":s3bucket is required") :type
    (common-lisp:or s3bucket common-lisp:null))
   (s3prefix-type common-lisp:nil :type
    (common-lisp:or s3object-name common-lisp:null)))
 (common-lisp:export (common-lisp:list 'output-config 'make-output-config))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape output-config))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "S3Bucket"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   's3bucket)))
    (aws-sdk-cl/generator/shape::to-query-params "S3Prefix"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   's3prefix))))))
(common-lisp:progn
 (common-lisp:deftype pages () '(trivial-types:proper-list uinteger))
 (common-lisp:defun |make-pages|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list uinteger))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype pagination-token () 'common-lisp:string)
(common-lisp:deftype percent () 'common-lisp:single-float)
(common-lisp:progn
 (common-lisp:defstruct (point (:copier common-lisp:nil))
   (xtype common-lisp:nil :type (common-lisp:or float common-lisp:null))
   (ytype common-lisp:nil :type (common-lisp:or float common-lisp:null)))
 (common-lisp:export (common-lisp:list 'point 'make-point))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape point))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "X"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'x)))
    (aws-sdk-cl/generator/shape::to-query-params "Y"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'y))))))
(common-lisp:progn
 (common-lisp:deftype polygon () '(trivial-types:proper-list point))
 (common-lisp:defun |make-polygon|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list point))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defstruct
     (provisioned-throughput-exceeded-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'provisioned-throughput-exceeded-exception
                    'make-provisioned-throughput-exceeded-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          provisioned-throughput-exceeded-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (relationship (:copier common-lisp:nil))
   (type-type common-lisp:nil :type
    (common-lisp:or relationship-type common-lisp:null))
   (ids-type common-lisp:nil :type (common-lisp:or id-list common-lisp:null)))
 (common-lisp:export (common-lisp:list 'relationship 'make-relationship))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape relationship))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Type"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'type)))
    (aws-sdk-cl/generator/shape::to-query-params "Ids"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'ids))))))
(common-lisp:progn
 (common-lisp:deftype relationship-list ()
   '(trivial-types:proper-list relationship))
 (common-lisp:defun |make-relationship-list|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list relationship))
   aws-sdk-cl/generator/shape::members))
(common-lisp:deftype relationship-type () 'common-lisp:string)
(common-lisp:deftype role-arn () 'common-lisp:string)
(common-lisp:deftype s3bucket () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (s3object (:copier common-lisp:nil))
   (bucket-type common-lisp:nil :type
    (common-lisp:or s3bucket common-lisp:null))
   (name-type common-lisp:nil :type
    (common-lisp:or s3object-name common-lisp:null))
   (version-type common-lisp:nil :type
    (common-lisp:or s3object-version common-lisp:null)))
 (common-lisp:export (common-lisp:list 's3object 'make-s3object))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape s3object))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "Bucket"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'bucket)))
    (aws-sdk-cl/generator/shape::to-query-params "Name"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'name)))
    (aws-sdk-cl/generator/shape::to-query-params "Version"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'version))))))
(common-lisp:deftype s3object-name () 'common-lisp:string)
(common-lisp:deftype s3object-version () 'common-lisp:string)
(common-lisp:deftype snstopic-arn () 'common-lisp:string)
(common-lisp:deftype selection-status () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct
     (start-document-analysis-request (:copier common-lisp:nil))
   (document-location-type (common-lisp:error ":document-location is required")
    :type (common-lisp:or document-location common-lisp:null))
   (feature-types-type (common-lisp:error ":feature-types is required") :type
    (common-lisp:or feature-types common-lisp:null))
   (client-request-token-type common-lisp:nil :type
    (common-lisp:or client-request-token common-lisp:null))
   (job-tag-type common-lisp:nil :type
    (common-lisp:or job-tag common-lisp:null))
   (notification-channel-type common-lisp:nil :type
    (common-lisp:or notification-channel common-lisp:null))
   (output-config-type common-lisp:nil :type
    (common-lisp:or output-config common-lisp:null))
   (kmskey-id-type common-lisp:nil :type
    (common-lisp:or kmskey-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-document-analysis-request
                    'make-start-document-analysis-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          start-document-analysis-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentLocation"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-location)))
    (aws-sdk-cl/generator/shape::to-query-params "FeatureTypes"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'feature-types)))
    (aws-sdk-cl/generator/shape::to-query-params "ClientRequestToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-request-token)))
    (aws-sdk-cl/generator/shape::to-query-params "JobTag"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-tag)))
    (aws-sdk-cl/generator/shape::to-query-params "NotificationChannel"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'notification-channel)))
    (aws-sdk-cl/generator/shape::to-query-params "OutputConfig"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'output-config)))
    (aws-sdk-cl/generator/shape::to-query-params "KMSKeyId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'kmskey-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (start-document-analysis-response (:copier common-lisp:nil))
   (job-id-type common-lisp:nil :type
    (common-lisp:or job-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-document-analysis-response
                    'make-start-document-analysis-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          start-document-analysis-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "JobId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (start-document-text-detection-request (:copier common-lisp:nil))
   (document-location-type (common-lisp:error ":document-location is required")
    :type (common-lisp:or document-location common-lisp:null))
   (client-request-token-type common-lisp:nil :type
    (common-lisp:or client-request-token common-lisp:null))
   (job-tag-type common-lisp:nil :type
    (common-lisp:or job-tag common-lisp:null))
   (notification-channel-type common-lisp:nil :type
    (common-lisp:or notification-channel common-lisp:null))
   (output-config-type common-lisp:nil :type
    (common-lisp:or output-config common-lisp:null))
   (kmskey-id-type common-lisp:nil :type
    (common-lisp:or kmskey-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-document-text-detection-request
                    'make-start-document-text-detection-request))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          start-document-text-detection-request))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "DocumentLocation"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'document-location)))
    (aws-sdk-cl/generator/shape::to-query-params "ClientRequestToken"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'client-request-token)))
    (aws-sdk-cl/generator/shape::to-query-params "JobTag"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-tag)))
    (aws-sdk-cl/generator/shape::to-query-params "NotificationChannel"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'notification-channel)))
    (aws-sdk-cl/generator/shape::to-query-params "OutputConfig"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'output-config)))
    (aws-sdk-cl/generator/shape::to-query-params "KMSKeyId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'kmskey-id))))))
(common-lisp:progn
 (common-lisp:defstruct
     (start-document-text-detection-response (:copier common-lisp:nil))
   (job-id-type common-lisp:nil :type
    (common-lisp:or job-id common-lisp:null)))
 (common-lisp:export
  (common-lisp:list 'start-document-text-detection-response
                    'make-start-document-text-detection-response))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          start-document-text-detection-response))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "JobId"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'job-id))))))
(common-lisp:deftype status-message () 'common-lisp:string)
(common-lisp:deftype string () 'common-lisp:string)
(common-lisp:deftype text-type () 'common-lisp:string)
(common-lisp:progn
 (common-lisp:defstruct (throttling-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'throttling-exception 'make-throttling-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          throttling-exception))
   (common-lisp:append)))
(common-lisp:deftype uinteger () 'common-lisp:integer)
(common-lisp:progn
 (common-lisp:defstruct
     (unsupported-document-exception (:copier common-lisp:nil)))
 (common-lisp:export
  (common-lisp:list 'unsupported-document-exception
                    'make-unsupported-document-exception))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        (
                         (aws-sdk-cl/generator/shape::shape
                          unsupported-document-exception))
   (common-lisp:append)))
(common-lisp:progn
 (common-lisp:defstruct (warning (:copier common-lisp:nil))
   (error-code-type common-lisp:nil :type
    (common-lisp:or error-code common-lisp:null))
   (pages-type common-lisp:nil :type (common-lisp:or pages common-lisp:null)))
 (common-lisp:export (common-lisp:list 'warning 'make-warning))
 (common-lisp:defmethod aws-sdk-cl/generator/shape:shape-to-params
                        ((aws-sdk-cl/generator/shape::shape warning))
   (common-lisp:append
    (aws-sdk-cl/generator/shape::to-query-params "ErrorCode"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'error-code)))
    (aws-sdk-cl/generator/shape::to-query-params "Pages"
                                                 (aws-sdk-cl/generator/shape:shape-to-params
                                                  (common-lisp:slot-value
                                                   aws-sdk-cl/generator/shape::shape
                                                   'pages))))))
(common-lisp:progn
 (common-lisp:deftype warnings () '(trivial-types:proper-list warning))
 (common-lisp:defun |make-warnings|
                    (common-lisp:&rest aws-sdk-cl/generator/shape::members)
   (common-lisp:check-type aws-sdk-cl/generator/shape::members
                           (trivial-types:proper-list warning))
   aws-sdk-cl/generator/shape::members))
(common-lisp:progn
 (common-lisp:defun analyze-document
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key document feature-types human-loop-config)
   (common-lisp:declare
    (common-lisp:ignorable document feature-types human-loop-config))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-analyze-document-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"AnalyzeDocument")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "AnalyzeDocumentResponse" common-lisp:nil)))
 (common-lisp:export 'analyze-document))
(common-lisp:progn
 (common-lisp:defun detect-document-text
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key document)
   (common-lisp:declare (common-lisp:ignorable document))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-detect-document-text-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"DetectDocumentText")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "DetectDocumentTextResponse" common-lisp:nil)))
 (common-lisp:export 'detect-document-text))
(common-lisp:progn
 (common-lisp:defun get-document-analysis
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key job-id max-results next-token)
   (common-lisp:declare (common-lisp:ignorable job-id max-results next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-get-document-analysis-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetDocumentAnalysis")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetDocumentAnalysisResponse" common-lisp:nil)))
 (common-lisp:export 'get-document-analysis))
(common-lisp:progn
 (common-lisp:defun get-document-text-detection
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key job-id max-results next-token)
   (common-lisp:declare (common-lisp:ignorable job-id max-results next-token))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-get-document-text-detection-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"GetDocumentTextDetection")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "GetDocumentTextDetectionResponse" common-lisp:nil)))
 (common-lisp:export 'get-document-text-detection))
(common-lisp:progn
 (common-lisp:defun start-document-analysis
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key document-location feature-types
                     client-request-token job-tag notification-channel
                     output-config kmskey-id)
   (common-lisp:declare
    (common-lisp:ignorable document-location feature-types client-request-token
     job-tag notification-channel output-config kmskey-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply 'make-start-document-analysis-request
                                         aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"StartDocumentAnalysis")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "StartDocumentAnalysisResponse" common-lisp:nil)))
 (common-lisp:export 'start-document-analysis))
(common-lisp:progn
 (common-lisp:defun start-document-text-detection
                    (
                     common-lisp:&rest aws-sdk-cl/generator/operation::args
                     common-lisp:&key document-location client-request-token
                     job-tag notification-channel output-config kmskey-id)
   (common-lisp:declare
    (common-lisp:ignorable document-location client-request-token job-tag
     notification-channel output-config kmskey-id))
   (common-lisp:let ((aws-sdk-cl/generator/operation::input
                      (common-lisp:apply
                       'make-start-document-text-detection-request
                       aws-sdk-cl/generator/operation::args)))
     (aws-sdk-cl/generator/operation::parse-response
      (aws-sdk-cl/api:aws-request :service "textract" :method :post :params
                                  (common-lisp:append
                                   `(("Action" ,@"StartDocumentTextDetection")
                                     ("Version" ,@"2018-06-27"))
                                   (aws-sdk-cl/generator/shape:shape-to-params
                                    aws-sdk-cl/generator/operation::input)))
      "StartDocumentTextDetectionResponse" common-lisp:nil)))
 (common-lisp:export 'start-document-text-detection))
